/**
 * Synthetic in-memory seed for development and tests. Performance METADATA ONLY — NO formulas,
 * NO metric calculation, NO statistical algorithms, no persistence. Strategies/portfolios/
 * backtests/live-sessions/simulations are referenced by ref so cross-links resolve; metric
 * VALUES, series points and benchmark values are inert strings produced by the analytics
 * runtime, nothing is computed here.
 */
import type {
  Benchmark,
  PerformanceComparison,
  PerformanceReport,
  ReportFamily,
} from '@platform/performance-sdk';

const SPX: Benchmark = {
  id: 'BM-SPX',
  name: 'S&P 500',
  kind: 'INDEX',
  ref: 'idx-spx',
  description: 'US large-cap equity index.',
};
const RISK_FREE: Benchmark = {
  id: 'BM-RF',
  name: '3M T-Bill',
  kind: 'RISK_FREE',
  ref: 'rf-3m',
  description: 'Risk-free rate proxy.',
};
const PEER: Benchmark = {
  id: 'BM-PEER',
  name: 'Market-neutral peers',
  kind: 'PEER',
  ref: 'peer-mn',
  description: 'Peer market-neutral composite.',
};

export const BENCHMARKS: readonly Benchmark[] = [SPX, RISK_FREE, PEER];

export const REPORTS: readonly PerformanceReport[] = [
  {
    id: 'PR-EQUITY-BT',
    slug: 'equity-reversal-backtest-perf',
    name: 'Equity reversal backtest performance',
    description: 'Published performance report for the reversal L/S historical backtest.',
    namespace: 'equities',
    family: 'reversal',
    stage: 'PUBLISHED',
    computation: 'COMPLETED',
    version: '2.0.0',
    subjectKind: 'BACKTEST',
    subjectRef: 'bt-reversal',
    subjectName: 'Reversal L/S historical',
    window: '2015-01-01 → 2025-12-31',
    metrics: [
      { key: 'total_return', value: '84.2%', definitionVersion: '1.0.0' },
      { key: 'annual_return', value: '9.1%', definitionVersion: '1.0.0' },
      { key: 'cagr', value: '8.7%', definitionVersion: '1.0.0' },
      { key: 'volatility', value: '8.7%', definitionVersion: '1.0.0' },
      { key: 'sharpe_ratio', value: '1.32', definitionVersion: '1.0.0' },
      { key: 'sortino_ratio', value: '1.81', definitionVersion: '1.0.0' },
      { key: 'calmar_ratio', value: '0.73', definitionVersion: '1.0.0' },
      { key: 'max_drawdown', value: '-12.4%', definitionVersion: '1.0.0' },
      { key: 'average_drawdown', value: '-3.1%', definitionVersion: '1.0.0' },
      { key: 'recovery_time', value: '54', definitionVersion: '1.0.0' },
      { key: 'win_rate', value: '54%', definitionVersion: '1.0.0' },
      { key: 'profit_factor', value: '1.42', definitionVersion: '1.0.0' },
      { key: 'expectancy', value: '$18', definitionVersion: '1.0.0' },
      { key: 'average_trade', value: '$21', definitionVersion: '1.0.0' },
      { key: 'turnover', value: '6.2x', definitionVersion: '1.0.0' },
      { key: 'exposure', value: '96%', definitionVersion: '1.0.0' },
      { key: 'alpha', value: '5.4%', definitionVersion: '1.0.0' },
      { key: 'beta', value: '0.05', definitionVersion: '1.0.0' },
      { key: 'information_ratio', value: '0.88', definitionVersion: '1.0.0' },
      { key: 'tracking_error', value: '6.1%', definitionVersion: '1.0.0' },
    ],
    series: [
      {
        id: 'SER-1',
        label: 'Equity curve',
        unit: 'index',
        points: [
          { t: '2015-01-01', value: '100' },
          { t: '2018-01-01', value: '128' },
          { t: '2021-01-01', value: '151' },
          { t: '2025-12-31', value: '184' },
        ],
      },
      {
        id: 'SER-2',
        label: 'Drawdown',
        unit: '%',
        points: [
          { t: '2015-01-01', value: '0' },
          { t: '2018-06-01', value: '-8.1' },
          { t: '2020-03-01', value: '-12.4' },
          { t: '2025-12-31', value: '-1.2' },
        ],
      },
    ],
    benchmark: {
      id: 'BC-1',
      benchmark: SPX,
      note: 'Reversal vs S&P 500.',
      rows: [
        { key: 'total_return', subjectValue: '84.2%', benchmarkValue: '142.0%' },
        { key: 'volatility', subjectValue: '8.7%', benchmarkValue: '15.4%' },
        { key: 'sharpe_ratio', subjectValue: '1.32', benchmarkValue: '0.71' },
        { key: 'max_drawdown', subjectValue: '-12.4%', benchmarkValue: '-33.9%' },
        { key: 'alpha', subjectValue: '5.4%', benchmarkValue: '0.0%' },
        { key: 'beta', subjectValue: '0.05', benchmarkValue: '1.00' },
      ],
    },
    validation: {
      status: 'PASSED',
      method: 'Report reproduction check',
      checkedAt: '2026-07-21T00:00:00.000Z',
      note: 'Reproduced from manifest.',
    },
    approval: 'APPROVED',
    reviews: [
      {
        id: 'PRV-1',
        reviewer: 'Analytics Review',
        stage: 'REVIEW',
        status: 'PASSED',
        reviewedAt: '2026-07-21T00:00:00.000Z',
      },
    ],
    approvals: [
      {
        id: 'PAP-1',
        role: 'Head of Research',
        status: 'APPROVED',
        decidedAt: '2026-07-22T00:00:00.000Z',
        rationale: 'Metrics reproduced; report published.',
      },
    ],
    artifacts: [
      { id: 'PART-1', kind: 'REPORT', ref: 'rep-equity-bt', name: 'Performance report' },
      { id: 'PART-2', kind: 'TEARSHEET', ref: 'tear-equity-bt', name: 'Tearsheet' },
      { id: 'PART-3', kind: 'MANIFEST', ref: 'man-equity-bt', name: 'Report manifest' },
    ],
    timeline: [
      {
        id: 'PTL-1',
        kind: 'COMPUTATION',
        label: 'Metrics computed',
        detail: 'Analytics runtime completed.',
        at: '2026-07-20T00:00:00.000Z',
      },
      {
        id: 'PTL-2',
        kind: 'APPROVAL',
        label: 'Approved',
        detail: 'Published.',
        at: '2026-07-22T00:00:00.000Z',
      },
    ],
    dependencies: [
      {
        id: 'PDEP-1',
        kind: 'BACKTEST',
        ref: 'bt-reversal',
        name: 'Reversal L/S historical',
        status: 'SATISFIED',
      },
      {
        id: 'PDEP-2',
        kind: 'STRATEGY',
        ref: 'str-reversal-ls',
        name: 'Reversal L/S strategy',
        status: 'SATISFIED',
      },
    ],
    versions: [
      {
        version: '2.0.0',
        stage: 'PUBLISHED',
        createdAt: '2026-07-22T00:00:00.000Z',
        note: 'Published.',
        manifestHash: 'sha256:pr20',
      },
      {
        version: '1.0.0',
        stage: 'ARCHIVED',
        createdAt: '2026-06-01T00:00:00.000Z',
        note: 'Prior report.',
        manifestHash: 'sha256:pr10',
      },
    ],
    snapshots: [
      {
        reportId: 'PR-EQUITY-BT',
        version: '2.0.0',
        stage: 'PUBLISHED',
        capturedAt: '2026-07-22T00:00:00.000Z',
        manifestHash: 'sha256:pr20',
      },
    ],
    owner: { owner: 'Ada Analyst', team: 'Analytics', steward: 'Analytics Guild' },
    tags: ['reversal', 'equity', 'backtest'],
    metadata: [
      { key: 'window', value: '2015–2025' },
      { key: 'benchmark', value: 'S&P 500' },
    ],
    registryRef: 'REG-pr-equity-bt',
    registeredAt: '2026-06-01T00:00:00.000Z',
    updatedAt: '2026-07-22T00:00:00.000Z',
  },
  {
    id: 'PR-EQUITY-PORT',
    slug: 'equity-mn-portfolio-perf',
    name: 'Equity market-neutral portfolio performance',
    description: 'Performance report for the equity market-neutral portfolio, under review.',
    namespace: 'equities',
    family: 'market-neutral',
    stage: 'REVIEW',
    computation: 'COMPLETED',
    version: '1.1.0',
    subjectKind: 'PORTFOLIO',
    subjectRef: 'pf-equity-mn',
    subjectName: 'Equity market-neutral',
    window: '2025-01-01 → 2025-12-31',
    metrics: [
      { key: 'total_return', value: '11.2%', definitionVersion: '1.0.0' },
      { key: 'cagr', value: '11.2%', definitionVersion: '1.0.0' },
      { key: 'volatility', value: '4.1%', definitionVersion: '1.0.0' },
      { key: 'sharpe_ratio', value: '1.48', definitionVersion: '1.0.0' },
      { key: 'sortino_ratio', value: '2.10', definitionVersion: '1.0.0' },
      { key: 'max_drawdown', value: '-3.8%', definitionVersion: '1.0.0' },
      { key: 'win_rate', value: '56%', definitionVersion: '1.0.0' },
      { key: 'turnover', value: '0.18x', definitionVersion: '1.0.0' },
      { key: 'exposure', value: '198%', definitionVersion: '1.0.0' },
      { key: 'alpha', value: '4.1%', definitionVersion: '1.0.0' },
      { key: 'beta', value: '0.02', definitionVersion: '1.0.0' },
      { key: 'information_ratio', value: '0.92', definitionVersion: '1.0.0' },
    ],
    series: [
      {
        id: 'SER-3',
        label: 'Equity curve',
        unit: 'index',
        points: [
          { t: '2025-01-01', value: '100' },
          { t: '2025-06-01', value: '106' },
          { t: '2025-12-31', value: '111' },
        ],
      },
    ],
    benchmark: {
      id: 'BC-2',
      benchmark: PEER,
      note: 'vs market-neutral peers.',
      rows: [
        { key: 'total_return', subjectValue: '11.2%', benchmarkValue: '7.8%' },
        { key: 'sharpe_ratio', subjectValue: '1.48', benchmarkValue: '1.10' },
        { key: 'max_drawdown', subjectValue: '-3.8%', benchmarkValue: '-5.2%' },
      ],
    },
    validation: {
      status: 'PASSED',
      method: 'Report reproduction check',
      checkedAt: '2026-07-28T00:00:00.000Z',
      note: 'Reproduced.',
    },
    approval: 'NOT_REQUESTED',
    reviews: [{ id: 'PRV-2', reviewer: 'Analytics Review', stage: 'REVIEW', status: 'PENDING' }],
    approvals: [],
    artifacts: [
      { id: 'PART-4', kind: 'REPORT', ref: 'rep-equity-port', name: 'Performance report' },
    ],
    timeline: [
      {
        id: 'PTL-3',
        kind: 'COMPUTATION',
        label: 'Metrics computed',
        detail: 'Analytics runtime completed.',
        at: '2026-07-28T00:00:00.000Z',
      },
    ],
    dependencies: [
      {
        id: 'PDEP-3',
        kind: 'PORTFOLIO',
        ref: 'pf-equity-mn',
        name: 'Equity market-neutral',
        status: 'SATISFIED',
      },
    ],
    versions: [
      {
        version: '1.1.0',
        stage: 'REVIEW',
        createdAt: '2026-07-28T00:00:00.000Z',
        note: 'Under review.',
        manifestHash: 'sha256:prp11',
      },
    ],
    snapshots: [
      {
        reportId: 'PR-EQUITY-PORT',
        version: '1.1.0',
        stage: 'REVIEW',
        capturedAt: '2026-07-28T00:00:00.000Z',
        manifestHash: 'sha256:prp11',
      },
    ],
    owner: { owner: 'Blaise Analyst', team: 'Analytics', steward: 'Analytics Guild' },
    tags: ['market-neutral', 'equity', 'portfolio'],
    metadata: [{ key: 'window', value: '2025' }],
    registryRef: 'REG-pr-equity-port',
    registeredAt: '2026-07-27T00:00:00.000Z',
    updatedAt: '2026-07-28T00:00:00.000Z',
  },
  {
    id: 'PR-FX-LIVE',
    slug: 'fx-carry-live-perf',
    name: 'FX carry live performance',
    description: 'Performance report for the live FX carry session, awaiting governance approval.',
    namespace: 'fx',
    family: 'carry',
    stage: 'REVIEW',
    computation: 'COMPLETED',
    version: '1.0.0',
    subjectKind: 'LIVE_SESSION',
    subjectRef: 'dep-fx-carry',
    subjectName: 'FX carry (live)',
    window: '2026-08-02 → 2026-08-03',
    metrics: [
      { key: 'total_return', value: '0.4%', definitionVersion: '1.0.0' },
      { key: 'volatility', value: '3.2%', definitionVersion: '1.0.0' },
      { key: 'sharpe_ratio', value: '0.9', definitionVersion: '1.0.0' },
      { key: 'max_drawdown', value: '-0.9%', definitionVersion: '1.0.0' },
      { key: 'win_rate', value: '52%', definitionVersion: '1.0.0' },
      { key: 'turnover', value: '1.1x', definitionVersion: '1.0.0' },
      { key: 'exposure', value: '36%', definitionVersion: '1.0.0' },
    ],
    series: [
      {
        id: 'SER-4',
        label: 'Equity curve',
        unit: 'index',
        points: [
          { t: '2026-08-02', value: '100' },
          { t: '2026-08-03', value: '100.4' },
        ],
      },
    ],
    benchmark: {
      id: 'BC-3',
      benchmark: RISK_FREE,
      note: 'vs risk-free.',
      rows: [{ key: 'total_return', subjectValue: '0.4%', benchmarkValue: '0.01%' }],
    },
    validation: {
      status: 'PASSED',
      method: 'Research↔production parity',
      checkedAt: '2026-08-03T00:00:00.000Z',
      note: 'Parity verified.',
    },
    approval: 'PENDING',
    reviews: [
      {
        id: 'PRV-3',
        reviewer: 'Analytics Review',
        stage: 'REVIEW',
        status: 'PASSED',
        reviewedAt: '2026-08-03T06:00:00.000Z',
      },
    ],
    approvals: [{ id: 'PAP-2', role: 'Head of Research', status: 'PENDING' }],
    artifacts: [{ id: 'PART-5', kind: 'REPORT', ref: 'rep-fx-live', name: 'Performance report' }],
    timeline: [
      {
        id: 'PTL-4',
        kind: 'REVIEW',
        label: 'Reviewed',
        detail: 'Passed review.',
        at: '2026-08-03T06:00:00.000Z',
      },
    ],
    dependencies: [
      {
        id: 'PDEP-4',
        kind: 'LIVE_SESSION',
        ref: 'dep-fx-carry',
        name: 'FX carry (paused)',
        status: 'SATISFIED',
      },
    ],
    versions: [
      {
        version: '1.0.0',
        stage: 'REVIEW',
        createdAt: '2026-08-03T00:00:00.000Z',
        note: 'Awaiting approval.',
        manifestHash: 'sha256:prfx10',
      },
    ],
    snapshots: [],
    owner: { owner: 'Cleo Analyst', team: 'Analytics', steward: 'Analytics Guild' },
    tags: ['carry', 'fx', 'live'],
    metadata: [{ key: 'window', value: '2026-08-02/03' }],
    registryRef: 'REG-pr-fx-live',
    registeredAt: '2026-08-03T00:00:00.000Z',
    updatedAt: '2026-08-03T06:00:00.000Z',
  },
  {
    id: 'PR-CRYPTO-SIM',
    slug: 'crypto-sim-perf',
    name: 'Crypto simulation performance',
    description: 'Performance report for a crypto simulation, computation in progress.',
    namespace: 'crypto',
    family: 'momentum',
    stage: 'REQUESTED',
    computation: 'RUNNING',
    version: '0.5.0',
    subjectKind: 'SIMULATION',
    subjectRef: 'sim-multi-asset',
    subjectName: 'Multi-asset risk-balanced sim',
    window: '2024-01-01 → 2025-12-31',
    metrics: [],
    series: [],
    validation: {
      status: 'PENDING',
      method: 'Report reproduction check',
      note: 'Awaiting computation.',
    },
    approval: 'NOT_REQUESTED',
    reviews: [],
    approvals: [],
    artifacts: [],
    timeline: [
      {
        id: 'PTL-5',
        kind: 'COMPUTATION',
        label: 'Computation requested',
        detail: 'Analytics runtime running.',
        at: '2026-08-03T00:00:00.000Z',
      },
    ],
    dependencies: [
      {
        id: 'PDEP-5',
        kind: 'SIMULATION',
        ref: 'sim-multi-asset',
        name: 'Multi-asset risk-balanced sim',
        status: 'PENDING',
      },
    ],
    versions: [
      {
        version: '0.5.0',
        stage: 'REQUESTED',
        createdAt: '2026-08-03T00:00:00.000Z',
        note: 'Computing.',
        manifestHash: 'sha256:prcs05',
      },
    ],
    snapshots: [],
    owner: { owner: 'Dara Analyst', team: 'Analytics', steward: 'Analytics Guild' },
    tags: ['crypto', 'simulation'],
    metadata: [{ key: 'window', value: '2024–2025' }],
    registryRef: 'REG-pr-crypto-sim',
    registeredAt: '2026-08-03T00:00:00.000Z',
    updatedAt: '2026-08-03T00:00:00.000Z',
  },
  {
    id: 'PR-VOL-STRAT',
    slug: 'vol-strategy-perf-draft',
    name: 'Vol strategy performance draft',
    description: 'Draft performance report for the volatility strategy.',
    namespace: 'equities',
    family: 'volatility',
    stage: 'DRAFT',
    computation: 'PENDING',
    version: '0.1.0',
    subjectKind: 'STRATEGY',
    subjectRef: 'str-vol-target',
    subjectName: 'Vol target strategy',
    window: '2020-01-01 → 2025-12-31',
    metrics: [],
    series: [],
    validation: {
      status: 'NOT_RUN',
      method: 'Report reproduction check',
      note: 'Not yet computed.',
    },
    approval: 'NOT_REQUESTED',
    reviews: [],
    approvals: [],
    artifacts: [],
    timeline: [
      {
        id: 'PTL-6',
        kind: 'REPORT',
        label: 'Report drafted',
        detail: 'Awaiting computation request.',
        at: '2026-08-02T00:00:00.000Z',
      },
    ],
    dependencies: [
      {
        id: 'PDEP-6',
        kind: 'STRATEGY',
        ref: 'str-vol-target',
        name: 'Vol target strategy',
        status: 'PENDING',
      },
    ],
    versions: [
      {
        version: '0.1.0',
        stage: 'DRAFT',
        createdAt: '2026-08-02T00:00:00.000Z',
        note: 'Draft.',
        manifestHash: 'sha256:prvs01',
      },
    ],
    snapshots: [],
    owner: { owner: 'Dara Analyst', team: 'Analytics', steward: 'Analytics Guild' },
    tags: ['volatility', 'strategy', 'draft'],
    metadata: [{ key: 'window', value: '2020–2025' }],
    registryRef: 'REG-pr-vol-strat',
    registeredAt: '2026-08-02T00:00:00.000Z',
    updatedAt: '2026-08-02T00:00:00.000Z',
  },
];

export const FAMILIES: readonly ReportFamily[] = [
  {
    namespace: 'equities',
    family: 'reversal',
    description: 'Reversal performance reports.',
    reportCount: 1,
  },
  {
    namespace: 'equities',
    family: 'market-neutral',
    description: 'Market-neutral performance reports.',
    reportCount: 1,
  },
  {
    namespace: 'equities',
    family: 'volatility',
    description: 'Volatility performance reports.',
    reportCount: 1,
  },
  {
    namespace: 'fx',
    family: 'carry',
    description: 'FX carry performance reports.',
    reportCount: 1,
  },
  {
    namespace: 'crypto',
    family: 'momentum',
    description: 'Crypto momentum performance reports.',
    reportCount: 1,
  },
];

export const COMPARISONS: readonly PerformanceComparison[] = [
  {
    id: 'PCMP-1',
    name: 'Reversal backtest vs MN portfolio',
    kind: 'MIXED',
    reportIds: ['PR-EQUITY-BT', 'PR-EQUITY-PORT'],
    metricKeys: ['total_return', 'sharpe_ratio', 'max_drawdown', 'alpha', 'information_ratio'],
    createdAt: '2026-07-29T00:00:00.000Z',
    note: 'Head-to-head of the two computed reports.',
  },
];
