/**
 * Execution Simulator DTOs. The canonical shapes are owned by the shared
 * `@platform/execution-sdk` (single source of truth across the service and this UI);
 * this module re-exports them so both tiers speak the same vocabulary. Inert data only
 * — no execution algorithm, no exchange/broker connectivity, no fill/price calculation.
 */
export type {
  ApprovalStatus,
  ArtifactKind,
  DependencyKind,
  DependencyStatus,
  ExecutionApproval,
  ExecutionArtifact,
  ExecutionDependency,
  ExecutionFill,
  ExecutionLineage,
  ExecutionMetric,
  ExecutionOrder,
  ExecutionOwner,
  ExecutionPortfolio,
  ExecutionPosition,
  ExecutionReplay,
  ExecutionReport,
  ExecutionReview,
  ExecutionSnapshot,
  ExecutionTimelineEvent,
  ExecutionValidation,
  ExecutionVersion,
  LineageNode,
  LineageNodeKind,
  Liquidity,
  MetadataEntry,
  MetricDescriptor,
  MetricKey,
  OrderSide,
  OrderStatus,
  OrderType,
  PositionSide,
  ReportKind,
  ReviewStatus,
  RunStatus,
  ScenarioTemplate,
  SessionRun,
  SimulationComparison,
  SimulationFamily,
  SimulationScenario,
  SimulationSession,
  SimulationStage,
  TimelineKind,
  ValidationStatus,
} from '@platform/execution-sdk';
