/**
 * Synthetic in-memory seed for development and tests. Deployment METADATA ONLY — NO
 * exchange/broker SDK, NO API keys, NO HTTP/REST client, NO WebSocket, NO FIX, NO order
 * execution, NO PnL/exposure computation, no persistence. Strategies/portfolios/
 * simulations/accounts are referenced by ref; credentials are referenced by opaque
 * `credentialRef` only; quantities, prices, balances, exposures and metric VALUES are
 * inert strings, nothing is computed or transmitted.
 */
import type {
  Deployment,
  DeploymentFamily,
  TradingAccount,
  BrokerConnection,
} from '@platform/trading-sdk';

export const ACCOUNTS: readonly TradingAccount[] = [
  {
    id: 'ACC-IB',
    name: 'IB institutional',
    brokerKind: 'TRADITIONAL_BROKER',
    provider: 'interactive-brokers',
    mode: 'LIVE',
    baseCurrency: 'USD',
    status: 'AUTHORIZED',
  },
  {
    id: 'ACC-ALPACA',
    name: 'Alpaca equities',
    brokerKind: 'TRADITIONAL_BROKER',
    provider: 'alpaca',
    mode: 'PAPER',
    baseCurrency: 'USD',
    status: 'CONFIGURED',
  },
  {
    id: 'ACC-BINANCE',
    name: 'Binance spot',
    brokerKind: 'CRYPTO_EXCHANGE',
    provider: 'binance',
    mode: 'SHADOW',
    baseCurrency: 'USDT',
    status: 'CONFIGURED',
  },
  {
    id: 'ACC-DERIBIT',
    name: 'Deribit options',
    brokerKind: 'OPTIONS_BROKER',
    provider: 'deribit',
    mode: 'PAPER',
    baseCurrency: 'USD',
    status: 'DISCONNECTED',
  },
  {
    id: 'ACC-BIST',
    name: 'BIST equities',
    brokerKind: 'TRADITIONAL_BROKER',
    provider: 'bist',
    mode: 'PAPER',
    baseCurrency: 'TRY',
    status: 'DISCONNECTED',
  },
];

export const CONNECTIONS: readonly BrokerConnection[] = [
  {
    id: 'CON-IB',
    provider: 'interactive-brokers',
    brokerKind: 'TRADITIONAL_BROKER',
    label: 'IB gateway',
    mode: 'LIVE',
    status: 'AUTHORIZED',
    credentialRef: 'secret://ib/prod',
    note: 'Abstraction only; resolved by secrets broker.',
  },
  {
    id: 'CON-ALPACA',
    provider: 'alpaca',
    brokerKind: 'TRADITIONAL_BROKER',
    label: 'Alpaca paper',
    mode: 'PAPER',
    status: 'CONFIGURED',
    credentialRef: 'secret://alpaca/paper',
    note: 'Abstraction only.',
  },
  {
    id: 'CON-BINANCE',
    provider: 'binance',
    brokerKind: 'CRYPTO_EXCHANGE',
    label: 'Binance shadow',
    mode: 'SHADOW',
    status: 'CONFIGURED',
    credentialRef: 'secret://binance/shadow',
    note: 'Abstraction only.',
  },
  {
    id: 'CON-HYPERLIQUID',
    provider: 'hyperliquid',
    brokerKind: 'CRYPTO_EXCHANGE',
    label: 'Hyperliquid',
    mode: 'PAPER',
    status: 'DISCONNECTED',
    credentialRef: 'secret://hyperliquid/paper',
    note: 'Abstraction only.',
  },
  {
    id: 'CON-DERIBIT',
    provider: 'deribit',
    brokerKind: 'OPTIONS_BROKER',
    label: 'Deribit',
    mode: 'PAPER',
    status: 'DISCONNECTED',
    credentialRef: 'secret://deribit/paper',
    note: 'Abstraction only.',
  },
  {
    id: 'CON-BIST',
    provider: 'bist',
    brokerKind: 'TRADITIONAL_BROKER',
    label: 'BIST',
    mode: 'PAPER',
    status: 'DISCONNECTED',
    credentialRef: 'secret://bist/paper',
    note: 'Abstraction only.',
  },
];

export const DEPLOYMENTS: readonly Deployment[] = [
  {
    id: 'DEP-EQUITY-MN',
    slug: 'equity-market-neutral-live',
    name: 'Equity market-neutral live',
    description:
      'Live production deployment of the equity market-neutral strategy under a valid authorization token.',
    namespace: 'equities',
    family: 'market-neutral',
    stage: 'RUNNING',
    mode: 'LIVE',
    version: '2.0.0',
    account: ACCOUNTS[0]!,
    connection: CONNECTIONS[0]!,
    session: {
      id: 'TS-1',
      label: 'US session 2026-08-03',
      mode: 'LIVE',
      startedAt: '2026-08-03T13:30:00.000Z',
      note: 'Regular hours.',
    },
    runtime: {
      id: 'RS-1',
      strategyRef: 'str-reversal-ls',
      status: 'RUNNING',
      mode: 'LIVE',
      uptime: '5d 04h',
      startedAt: '2026-07-29T13:30:00.000Z',
      note: 'Nominal.',
    },
    authorization: {
      ref: 'auth://deploy/equity-mn/2',
      issuedBy: 'Deployment Governance',
      issuedAt: '2026-07-29T00:00:00.000Z',
      expiresAt: '2026-08-29T00:00:00.000Z',
      scope: 'equities/market-neutral',
      valid: true,
    },
    orders: [
      {
        id: 'TO-1',
        clientOrderId: 'P-1001',
        symbol: 'AAPL',
        side: 'BUY',
        type: 'LIMIT',
        quantity: '1200',
        limitPrice: '188.50',
        filledQuantity: '1200',
        status: 'FILLED',
        createdAt: '2026-08-03T13:31:00.000Z',
      },
      {
        id: 'TO-2',
        clientOrderId: 'P-1002',
        symbol: 'MSFT',
        side: 'BUY',
        type: 'LIMIT',
        quantity: '800',
        limitPrice: '410.00',
        filledQuantity: '500',
        status: 'PARTIALLY_FILLED',
        createdAt: '2026-08-03T13:32:00.000Z',
      },
      {
        id: 'TO-3',
        clientOrderId: 'P-1003',
        symbol: 'XYZ',
        side: 'SELL',
        type: 'MARKET',
        quantity: '900',
        filledQuantity: '0',
        status: 'ACCEPTED',
        createdAt: '2026-08-03T13:33:00.000Z',
      },
    ],
    positions: [
      {
        id: 'TP-1',
        symbol: 'AAPL',
        side: 'LONG',
        quantity: '1200',
        averagePrice: '188.42',
        marketValue: '226104',
        unrealizedPnl: '96',
        realizedPnl: '0',
        open: true,
      },
      {
        id: 'TP-2',
        symbol: 'MSFT',
        side: 'LONG',
        quantity: '500',
        averagePrice: '409.90',
        marketValue: '204950',
        unrealizedPnl: '50',
        realizedPnl: '0',
        open: true,
      },
      {
        id: 'TP-3',
        symbol: 'OLD',
        side: 'FLAT',
        quantity: '0',
        averagePrice: '0',
        marketValue: '0',
        unrealizedPnl: '0',
        realizedPnl: '420',
        open: false,
      },
    ],
    portfolio: {
      baseCurrency: 'USD',
      equity: '1000000',
      cash: '568946',
      grossExposure: '431054',
      netExposure: '431054',
      realizedPnl: '420',
      unrealizedPnl: '146',
    },
    balances: [
      {
        id: 'BAL-1',
        accountId: 'ACC-IB',
        asset: 'USD',
        total: '1000000',
        available: '568946',
        reserved: '431054',
      },
    ],
    permissions: [
      {
        id: 'PERM-1',
        capability: 'place-orders',
        granted: true,
        note: 'Authorized under live token.',
      },
      { id: 'PERM-2', capability: 'cancel-orders', granted: true, note: 'Authorized.' },
      {
        id: 'PERM-3',
        capability: 'withdraw',
        granted: false,
        note: 'Never granted to strategies.',
      },
    ],
    health: {
      status: 'HEALTHY',
      checkedAt: '2026-08-03T14:00:00.000Z',
      note: 'All checks green.',
      checks: [
        { id: 'HC-1', label: 'Connection', status: 'HEALTHY', detail: 'Gateway authorized.' },
        { id: 'HC-2', label: 'Order flow', status: 'HEALTHY', detail: 'Latency nominal.' },
        { id: 'HC-3', label: 'Risk limits', status: 'HEALTHY', detail: 'Within limits.' },
      ],
    },
    metrics: [
      { key: 'realized_pnl', value: '$420' },
      { key: 'unrealized_pnl', value: '$146' },
      { key: 'gross_exposure', value: '$431,054' },
      { key: 'net_exposure', value: '$431,054' },
      { key: 'open_orders', value: '1' },
      { key: 'open_positions', value: '2' },
      { key: 'fill_rate', value: '94%' },
      { key: 'uptime', value: '99.9%' },
      { key: 'error_rate', value: '0.2%' },
      { key: 'order_latency', value: '42ms' },
    ],
    timeline: [
      {
        id: 'TL-1',
        kind: 'DEPLOYMENT',
        label: 'Deployment activated',
        detail: 'Live under authorization token.',
        at: '2026-07-29T13:30:00.000Z',
      },
      {
        id: 'TL-2',
        kind: 'ORDER',
        label: 'Order filled',
        detail: 'AAPL 1200 @ 188.42.',
        at: '2026-08-03T13:31:02.000Z',
      },
      {
        id: 'TL-3',
        kind: 'HEALTH',
        label: 'Health check',
        detail: 'All green.',
        at: '2026-08-03T14:00:00.000Z',
      },
    ],
    approvals: [
      {
        id: 'AP-1',
        role: 'Chief Risk Officer',
        kind: 'RISK',
        status: 'APPROVED',
        decidedAt: '2026-07-28T00:00:00.000Z',
        rationale: 'Within risk envelope.',
        counterSignedBy: 'Head of Risk',
      },
      {
        id: 'AP-2',
        role: 'Deployment Governance',
        kind: 'DEPLOYMENT',
        status: 'APPROVED',
        decidedAt: '2026-07-29T00:00:00.000Z',
        rationale: 'Token issued.',
        counterSignedBy: 'CTO',
      },
    ],
    emergencyActions: [],
    killSwitch: { status: 'ARMED', armedBy: 'Trading Ops', note: 'Armed and ready; not engaged.' },
    validation: {
      status: 'PASSED',
      method: 'Pre-deployment checklist',
      checkedAt: '2026-07-28T12:00:00.000Z',
      note: 'Parity with simulation verified.',
    },
    dependencies: [
      {
        id: 'DEP-D1',
        kind: 'STRATEGY',
        ref: 'str-reversal-ls',
        name: 'Reversal L/S strategy',
        status: 'SATISFIED',
      },
      {
        id: 'DEP-D2',
        kind: 'PORTFOLIO',
        ref: 'pf-equity-mn',
        name: 'Equity market-neutral',
        status: 'SATISFIED',
      },
      {
        id: 'DEP-D3',
        kind: 'SIMULATION',
        ref: 'sim-equity-mn',
        name: 'Equity market-neutral sim',
        status: 'SATISFIED',
      },
    ],
    lineage: {
      nodes: [
        { id: 'N-1', kind: 'PORTFOLIO', ref: 'pf-equity-mn', label: 'Equity market-neutral' },
        { id: 'N-2', kind: 'SIMULATION', ref: 'sim-equity-mn', label: 'Equity market-neutral sim' },
        {
          id: 'N-3',
          kind: 'DEPLOYMENT',
          ref: 'dep-equity-mn',
          label: 'Equity market-neutral live',
        },
      ],
      edges: [
        { from: 'N-1', to: 'N-3' },
        { from: 'N-2', to: 'N-3' },
      ],
    },
    audit: [
      {
        id: 'AUD-1',
        kind: 'APPROVAL',
        actor: 'Chief Risk Officer',
        action: 'Risk approved',
        detail: 'Within envelope.',
        occurredAt: '2026-07-28T00:00:00.000Z',
      },
      {
        id: 'AUD-2',
        kind: 'DEPLOYMENT',
        actor: 'Deployment Governance',
        action: 'Authorization issued',
        detail: 'Live token granted.',
        occurredAt: '2026-07-29T00:00:00.000Z',
      },
      {
        id: 'AUD-3',
        kind: 'RUNTIME',
        actor: 'live-trading',
        action: 'Activated',
        detail: 'Deployment running.',
        occurredAt: '2026-07-29T13:30:00.000Z',
      },
    ],
    versions: [
      {
        version: '2.0.0',
        stage: 'RUNNING',
        createdAt: '2026-07-29T00:00:00.000Z',
        note: 'Live.',
        manifestHash: 'sha256:dep20',
      },
      {
        version: '1.0.0',
        stage: 'ARCHIVED',
        createdAt: '2026-06-01T00:00:00.000Z',
        note: 'Prior cycle.',
        manifestHash: 'sha256:dep10',
      },
    ],
    snapshots: [
      {
        deploymentId: 'DEP-EQUITY-MN',
        version: '2.0.0',
        stage: 'RUNNING',
        capturedAt: '2026-07-29T00:00:00.000Z',
        manifestHash: 'sha256:dep20',
      },
    ],
    owner: { owner: 'Ada Trader', team: 'Production Trading', steward: 'Trading Guild' },
    tags: ['market-neutral', 'equity', 'live'],
    metadata: [
      { key: 'mandate', value: 'US market-neutral' },
      { key: 'mode', value: 'live' },
    ],
    strategyRef: 'str-reversal-ls',
    portfolioRef: 'pf-equity-mn',
    simulationRef: 'sim-equity-mn',
    registryRef: 'REG-dep-equity-mn',
    registeredAt: '2026-07-27T00:00:00.000Z',
    updatedAt: '2026-08-03T14:00:00.000Z',
  },
  {
    id: 'DEP-CRYPTO-MOM',
    slug: 'crypto-momentum-shadow',
    name: 'Crypto momentum shadow',
    description:
      'Shadow-mode production deployment of the crypto momentum strategy (no live token).',
    namespace: 'crypto',
    family: 'momentum',
    stage: 'RUNNING',
    mode: 'SHADOW',
    version: '1.0.0',
    account: ACCOUNTS[2]!,
    connection: CONNECTIONS[2]!,
    session: {
      id: 'TS-2',
      label: 'Continuous',
      mode: 'SHADOW',
      startedAt: '2026-08-01T00:00:00.000Z',
      note: '24/7 shadow.',
    },
    runtime: {
      id: 'RS-2',
      strategyRef: 'str-crypto-mom',
      status: 'RUNNING',
      mode: 'SHADOW',
      uptime: '2d 14h',
      startedAt: '2026-08-01T00:00:00.000Z',
      note: 'Shadowing live prices; no capital at risk.',
    },
    orders: [
      {
        id: 'TO-4',
        clientOrderId: 'S-2001',
        symbol: 'BTCUSDT',
        side: 'BUY',
        type: 'LIMIT',
        quantity: '1.5',
        limitPrice: '61000',
        filledQuantity: '1.5',
        status: 'FILLED',
        createdAt: '2026-08-03T10:00:00.000Z',
      },
    ],
    positions: [
      {
        id: 'TP-4',
        symbol: 'BTCUSDT',
        side: 'LONG',
        quantity: '1.5',
        averagePrice: '60980',
        marketValue: '91800',
        unrealizedPnl: '270',
        realizedPnl: '0',
        open: true,
      },
    ],
    portfolio: {
      baseCurrency: 'USDT',
      equity: '500000',
      cash: '408200',
      grossExposure: '91800',
      netExposure: '91800',
      realizedPnl: '0',
      unrealizedPnl: '270',
    },
    balances: [
      {
        id: 'BAL-2',
        accountId: 'ACC-BINANCE',
        asset: 'USDT',
        total: '500000',
        available: '408200',
        reserved: '91800',
      },
    ],
    permissions: [
      { id: 'PERM-4', capability: 'place-orders', granted: true, note: 'Shadow only.' },
    ],
    health: {
      status: 'HEALTHY',
      checkedAt: '2026-08-03T14:00:00.000Z',
      note: 'Shadow healthy.',
      checks: [{ id: 'HC-4', label: 'Feed', status: 'HEALTHY', detail: 'Market data live.' }],
    },
    metrics: [
      { key: 'realized_pnl', value: '$0' },
      { key: 'unrealized_pnl', value: '$270' },
      { key: 'open_orders', value: '0' },
      { key: 'open_positions', value: '1' },
      { key: 'fill_rate', value: '100%' },
      { key: 'uptime', value: '99.7%' },
      { key: 'error_rate', value: '0.1%' },
      { key: 'order_latency', value: '85ms' },
    ],
    timeline: [
      {
        id: 'TL-4',
        kind: 'DEPLOYMENT',
        label: 'Shadow started',
        detail: 'No capital at risk.',
        at: '2026-08-01T00:00:00.000Z',
      },
    ],
    approvals: [
      {
        id: 'AP-3',
        role: 'Chief Risk Officer',
        kind: 'RISK',
        status: 'APPROVED',
        decidedAt: '2026-07-31T00:00:00.000Z',
        rationale: 'Shadow-only; low risk.',
      },
    ],
    emergencyActions: [],
    killSwitch: { status: 'ARMED', armedBy: 'Trading Ops', note: 'Armed.' },
    validation: {
      status: 'PASSED',
      method: 'Pre-deployment checklist',
      checkedAt: '2026-07-31T00:00:00.000Z',
      note: 'Shadow validated.',
    },
    dependencies: [
      {
        id: 'DEP-D4',
        kind: 'STRATEGY',
        ref: 'str-crypto-mom',
        name: 'Crypto momentum',
        status: 'SATISFIED',
      },
      {
        id: 'DEP-D5',
        kind: 'SIMULATION',
        ref: 'sim-credit-carry',
        name: 'Credit carry sim',
        status: 'SATISFIED',
      },
    ],
    lineage: {
      nodes: [
        { id: 'N-1', kind: 'STRATEGY', ref: 'str-crypto-mom', label: 'Crypto momentum' },
        { id: 'N-2', kind: 'DEPLOYMENT', ref: 'dep-crypto-mom', label: 'Crypto momentum shadow' },
      ],
      edges: [{ from: 'N-1', to: 'N-2' }],
    },
    audit: [
      {
        id: 'AUD-4',
        kind: 'RUNTIME',
        actor: 'live-trading',
        action: 'Shadow started',
        detail: 'No capital at risk.',
        occurredAt: '2026-08-01T00:00:00.000Z',
      },
    ],
    versions: [
      {
        version: '1.0.0',
        stage: 'RUNNING',
        createdAt: '2026-08-01T00:00:00.000Z',
        note: 'Shadow.',
        manifestHash: 'sha256:depcm10',
      },
    ],
    snapshots: [
      {
        deploymentId: 'DEP-CRYPTO-MOM',
        version: '1.0.0',
        stage: 'RUNNING',
        capturedAt: '2026-08-01T00:00:00.000Z',
        manifestHash: 'sha256:depcm10',
      },
    ],
    owner: { owner: 'Blaise Trader', team: 'Crypto Trading', steward: 'Trading Guild' },
    tags: ['momentum', 'crypto', 'shadow'],
    metadata: [{ key: 'mode', value: 'shadow' }],
    strategyRef: 'str-crypto-mom',
    simulationRef: 'sim-credit-carry',
    registryRef: 'REG-dep-crypto-mom',
    registeredAt: '2026-07-31T00:00:00.000Z',
    updatedAt: '2026-08-03T14:00:00.000Z',
  },
  {
    id: 'DEP-MULTI-ASSET',
    slug: 'multi-asset-deploy-request',
    name: 'Multi-asset deploy request',
    description: 'Multi-asset deployment awaiting deployment-governance approval (paper-first).',
    namespace: 'multi-asset',
    family: 'risk-balanced',
    stage: 'DEPLOYMENT_APPROVAL',
    mode: 'PAPER',
    version: '0.9.0',
    account: ACCOUNTS[1]!,
    connection: CONNECTIONS[1]!,
    runtime: {
      id: 'RS-3',
      strategyRef: 'str-fx-carry',
      status: 'PENDING',
      mode: 'PAPER',
      uptime: '—',
      note: 'Awaiting approval; not started.',
    },
    orders: [],
    positions: [],
    portfolio: {
      baseCurrency: 'USD',
      equity: '2000000',
      cash: '2000000',
      grossExposure: '0',
      netExposure: '0',
      realizedPnl: '0',
      unrealizedPnl: '0',
    },
    balances: [
      {
        id: 'BAL-3',
        accountId: 'ACC-ALPACA',
        asset: 'USD',
        total: '2000000',
        available: '2000000',
        reserved: '0',
      },
    ],
    permissions: [
      { id: 'PERM-5', capability: 'place-orders', granted: false, note: 'Not yet authorized.' },
    ],
    health: { status: 'UNKNOWN', note: 'Not started.', checks: [] },
    metrics: [
      { key: 'open_orders', value: '0' },
      { key: 'open_positions', value: '0' },
    ],
    timeline: [
      {
        id: 'TL-5',
        kind: 'DEPLOYMENT',
        label: 'Deployment requested',
        detail: 'Awaiting approval.',
        at: '2026-08-02T00:00:00.000Z',
      },
    ],
    approvals: [
      {
        id: 'AP-4',
        role: 'Chief Risk Officer',
        kind: 'RISK',
        status: 'APPROVED',
        decidedAt: '2026-08-02T00:00:00.000Z',
        rationale: 'Risk cleared.',
      },
      { id: 'AP-5', role: 'Deployment Governance', kind: 'DEPLOYMENT', status: 'PENDING' },
    ],
    emergencyActions: [],
    killSwitch: { status: 'ARMED', armedBy: 'Trading Ops', note: 'Armed.' },
    validation: {
      status: 'PASSED',
      method: 'Pre-deployment checklist',
      checkedAt: '2026-08-02T00:00:00.000Z',
      note: 'Ready pending governance.',
    },
    dependencies: [
      {
        id: 'DEP-D6',
        kind: 'PORTFOLIO',
        ref: 'pf-multi-asset',
        name: 'Multi-asset risk-balanced',
        status: 'SATISFIED',
      },
    ],
    lineage: {
      nodes: [
        { id: 'N-1', kind: 'PORTFOLIO', ref: 'pf-multi-asset', label: 'Multi-asset risk-balanced' },
        {
          id: 'N-2',
          kind: 'DEPLOYMENT',
          ref: 'dep-multi-asset',
          label: 'Multi-asset deploy request',
        },
      ],
      edges: [{ from: 'N-1', to: 'N-2' }],
    },
    audit: [
      {
        id: 'AUD-5',
        kind: 'APPROVAL',
        actor: 'live-trading',
        action: 'Deployment approval requested',
        detail: 'Pending governance.',
        occurredAt: '2026-08-02T00:00:00.000Z',
      },
    ],
    versions: [
      {
        version: '0.9.0',
        stage: 'DEPLOYMENT_APPROVAL',
        createdAt: '2026-08-02T00:00:00.000Z',
        note: 'Awaiting approval.',
        manifestHash: 'sha256:depma09',
      },
    ],
    snapshots: [],
    owner: { owner: 'Cleo Trader', team: 'Multi-asset Trading', steward: 'Trading Guild' },
    tags: ['risk-balanced', 'multi-asset', 'approval'],
    metadata: [{ key: 'mode', value: 'paper' }],
    strategyRef: 'str-fx-carry',
    portfolioRef: 'pf-multi-asset',
    registryRef: 'REG-dep-multi-asset',
    registeredAt: '2026-08-02T00:00:00.000Z',
    updatedAt: '2026-08-02T00:00:00.000Z',
  },
  {
    id: 'DEP-FX-CARRY',
    slug: 'fx-carry-paused',
    name: 'FX carry (paused)',
    description: 'Live FX carry deployment currently paused by an operator.',
    namespace: 'fx',
    family: 'carry',
    stage: 'PAUSED',
    mode: 'LIVE',
    version: '1.2.0',
    account: ACCOUNTS[0]!,
    connection: CONNECTIONS[0]!,
    session: {
      id: 'TS-3',
      label: 'London session',
      mode: 'LIVE',
      startedAt: '2026-08-03T07:00:00.000Z',
      note: 'Paused mid-session.',
    },
    runtime: {
      id: 'RS-4',
      strategyRef: 'str-fx-carry',
      status: 'PAUSED',
      mode: 'LIVE',
      uptime: '1d 02h',
      startedAt: '2026-08-02T07:00:00.000Z',
      note: 'Paused pending a data review.',
    },
    authorization: {
      ref: 'auth://deploy/fx-carry/1',
      issuedBy: 'Deployment Governance',
      issuedAt: '2026-08-01T00:00:00.000Z',
      expiresAt: '2026-09-01T00:00:00.000Z',
      scope: 'fx/carry',
      valid: true,
    },
    orders: [
      {
        id: 'TO-5',
        clientOrderId: 'P-3001',
        symbol: 'EURUSD',
        side: 'BUY',
        type: 'LIMIT',
        quantity: '1000000',
        limitPrice: '1.0850',
        filledQuantity: '1000000',
        status: 'FILLED',
        createdAt: '2026-08-02T07:05:00.000Z',
      },
    ],
    positions: [
      {
        id: 'TP-5',
        symbol: 'EURUSD',
        side: 'LONG',
        quantity: '1000000',
        averagePrice: '1.0849',
        marketValue: '1084900',
        unrealizedPnl: '-120',
        realizedPnl: '340',
        open: true,
      },
    ],
    portfolio: {
      baseCurrency: 'USD',
      equity: '3000000',
      cash: '1915100',
      grossExposure: '1084900',
      netExposure: '1084900',
      realizedPnl: '340',
      unrealizedPnl: '-120',
    },
    balances: [
      {
        id: 'BAL-4',
        accountId: 'ACC-IB',
        asset: 'USD',
        total: '3000000',
        available: '1915100',
        reserved: '1084900',
      },
    ],
    permissions: [
      { id: 'PERM-6', capability: 'place-orders', granted: true, note: 'Authorized (paused).' },
    ],
    health: {
      status: 'DEGRADED',
      checkedAt: '2026-08-03T12:00:00.000Z',
      note: 'Paused; data feed under review.',
      checks: [
        { id: 'HC-5', label: 'Data feed', status: 'DEGRADED', detail: 'Intermittent gaps.' },
        { id: 'HC-6', label: 'Connection', status: 'HEALTHY', detail: 'Authorized.' },
      ],
    },
    metrics: [
      { key: 'realized_pnl', value: '$340' },
      { key: 'unrealized_pnl', value: '-$120' },
      { key: 'open_orders', value: '0' },
      { key: 'open_positions', value: '1' },
      { key: 'uptime', value: '98.2%' },
      { key: 'error_rate', value: '1.1%' },
      { key: 'order_latency', value: '55ms' },
    ],
    timeline: [
      {
        id: 'TL-6',
        kind: 'DEPLOYMENT',
        label: 'Deployment activated',
        detail: 'Live.',
        at: '2026-08-02T07:00:00.000Z',
      },
      {
        id: 'TL-7',
        kind: 'EMERGENCY',
        label: 'Paused',
        detail: 'Operator paused for data review.',
        at: '2026-08-03T08:00:00.000Z',
      },
    ],
    approvals: [
      {
        id: 'AP-6',
        role: 'Chief Risk Officer',
        kind: 'RISK',
        status: 'APPROVED',
        decidedAt: '2026-07-31T00:00:00.000Z',
        rationale: 'Within envelope.',
      },
      {
        id: 'AP-7',
        role: 'Deployment Governance',
        kind: 'DEPLOYMENT',
        status: 'APPROVED',
        decidedAt: '2026-08-01T00:00:00.000Z',
        rationale: 'Token issued.',
      },
    ],
    emergencyActions: [
      {
        id: 'EA-1',
        kind: 'PAUSE',
        actor: 'Dana Ops',
        reason: 'Data feed anomaly.',
        at: '2026-08-03T08:00:00.000Z',
      },
    ],
    killSwitch: { status: 'ARMED', armedBy: 'Trading Ops', note: 'Armed.' },
    validation: {
      status: 'PASSED',
      method: 'Pre-deployment checklist',
      checkedAt: '2026-07-31T12:00:00.000Z',
      note: 'Verified.',
    },
    dependencies: [
      {
        id: 'DEP-D7',
        kind: 'STRATEGY',
        ref: 'str-fx-carry',
        name: 'FX carry strategy',
        status: 'SATISFIED',
      },
    ],
    lineage: {
      nodes: [
        { id: 'N-1', kind: 'STRATEGY', ref: 'str-fx-carry', label: 'FX carry strategy' },
        { id: 'N-2', kind: 'DEPLOYMENT', ref: 'dep-fx-carry', label: 'FX carry (paused)' },
      ],
      edges: [{ from: 'N-1', to: 'N-2' }],
    },
    audit: [
      {
        id: 'AUD-6',
        kind: 'RUNTIME',
        actor: 'live-trading',
        action: 'Activated',
        detail: 'Live.',
        occurredAt: '2026-08-02T07:00:00.000Z',
      },
      {
        id: 'AUD-7',
        kind: 'EMERGENCY',
        actor: 'Dana Ops',
        action: 'Paused',
        detail: 'Data review.',
        occurredAt: '2026-08-03T08:00:00.000Z',
      },
    ],
    versions: [
      {
        version: '1.2.0',
        stage: 'PAUSED',
        createdAt: '2026-08-02T07:00:00.000Z',
        note: 'Paused.',
        manifestHash: 'sha256:depfx12',
      },
    ],
    snapshots: [
      {
        deploymentId: 'DEP-FX-CARRY',
        version: '1.2.0',
        stage: 'PAUSED',
        capturedAt: '2026-08-03T08:00:00.000Z',
        manifestHash: 'sha256:depfx12',
      },
    ],
    owner: { owner: 'Dana Ops', team: 'Macro Trading', steward: 'Trading Guild' },
    tags: ['carry', 'fx', 'paused', 'live'],
    metadata: [{ key: 'mode', value: 'live' }],
    strategyRef: 'str-fx-carry',
    registryRef: 'REG-dep-fx-carry',
    registeredAt: '2026-07-31T00:00:00.000Z',
    updatedAt: '2026-08-03T08:00:00.000Z',
  },
  {
    id: 'DEP-VOL-HALTED',
    slug: 'vol-target-halted',
    name: 'Vol target (kill-switched)',
    description:
      'Volatility-target deployment halted by the kill switch after a limit breach; stopped.',
    namespace: 'equities',
    family: 'volatility',
    stage: 'STOPPED',
    mode: 'LIVE',
    version: '0.4.0',
    account: ACCOUNTS[0]!,
    connection: CONNECTIONS[0]!,
    runtime: {
      id: 'RS-5',
      strategyRef: 'str-vol-target',
      status: 'HALTED',
      mode: 'LIVE',
      uptime: '0h',
      startedAt: '2026-07-25T00:00:00.000Z',
      note: 'Halted by kill switch.',
    },
    authorization: {
      ref: 'auth://deploy/vol/0',
      issuedBy: 'Deployment Governance',
      issuedAt: '2026-07-24T00:00:00.000Z',
      expiresAt: '2026-07-26T00:00:00.000Z',
      scope: 'equities/volatility',
      valid: false,
    },
    orders: [
      {
        id: 'TO-6',
        clientOrderId: 'P-5001',
        symbol: 'SPX',
        side: 'SELL',
        type: 'LIMIT',
        quantity: '10',
        limitPrice: '5200',
        filledQuantity: '0',
        status: 'CANCELLED',
        createdAt: '2026-07-25T14:00:00.000Z',
      },
    ],
    positions: [
      {
        id: 'TP-6',
        symbol: 'SPX',
        side: 'FLAT',
        quantity: '0',
        averagePrice: '0',
        marketValue: '0',
        unrealizedPnl: '0',
        realizedPnl: '-1250',
        open: false,
      },
    ],
    portfolio: {
      baseCurrency: 'USD',
      equity: '998750',
      cash: '998750',
      grossExposure: '0',
      netExposure: '0',
      realizedPnl: '-1250',
      unrealizedPnl: '0',
    },
    balances: [
      {
        id: 'BAL-5',
        accountId: 'ACC-IB',
        asset: 'USD',
        total: '998750',
        available: '998750',
        reserved: '0',
      },
    ],
    permissions: [
      { id: 'PERM-7', capability: 'place-orders', granted: false, note: 'Revoked on halt.' },
    ],
    health: {
      status: 'UNHEALTHY',
      checkedAt: '2026-07-25T14:30:00.000Z',
      note: 'Halted after limit breach.',
      checks: [
        {
          id: 'HC-7',
          label: 'Risk limits',
          status: 'UNHEALTHY',
          detail: 'Limit breached; halted.',
        },
      ],
    },
    metrics: [
      { key: 'realized_pnl', value: '-$1,250' },
      { key: 'open_orders', value: '0' },
      { key: 'open_positions', value: '0' },
      { key: 'uptime', value: '0%' },
      { key: 'error_rate', value: '—' },
    ],
    timeline: [
      {
        id: 'TL-8',
        kind: 'DEPLOYMENT',
        label: 'Deployment activated',
        detail: 'Live.',
        at: '2026-07-25T00:00:00.000Z',
      },
      {
        id: 'TL-9',
        kind: 'EMERGENCY',
        label: 'Kill switch engaged',
        detail: 'Limit breach; forced halt.',
        at: '2026-07-25T14:15:00.000Z',
      },
    ],
    approvals: [
      {
        id: 'AP-8',
        role: 'Chief Risk Officer',
        kind: 'RISK',
        status: 'APPROVED',
        decidedAt: '2026-07-23T00:00:00.000Z',
        rationale: 'Approved (pre-breach).',
      },
      {
        id: 'AP-9',
        role: 'Deployment Governance',
        kind: 'DEPLOYMENT',
        status: 'APPROVED',
        decidedAt: '2026-07-24T00:00:00.000Z',
        rationale: 'Token issued (now expired).',
      },
    ],
    emergencyActions: [
      {
        id: 'EA-2',
        kind: 'KILL_SWITCH',
        actor: 'Erin Risk',
        reason: 'Risk limit breach.',
        at: '2026-07-25T14:15:00.000Z',
      },
      {
        id: 'EA-3',
        kind: 'STOP',
        actor: 'Trading Ops',
        reason: 'Post-halt shutdown.',
        at: '2026-07-25T15:00:00.000Z',
      },
    ],
    killSwitch: {
      status: 'ENGAGED',
      armedBy: 'Trading Ops',
      engagedBy: 'Erin Risk',
      engagedAt: '2026-07-25T14:15:00.000Z',
      note: 'Engaged after limit breach.',
    },
    validation: {
      status: 'PASSED',
      method: 'Pre-deployment checklist',
      checkedAt: '2026-07-23T12:00:00.000Z',
      note: 'Was valid at deploy.',
    },
    dependencies: [
      {
        id: 'DEP-D8',
        kind: 'STRATEGY',
        ref: 'str-vol-target',
        name: 'Vol target strategy',
        status: 'SATISFIED',
      },
    ],
    lineage: {
      nodes: [
        { id: 'N-1', kind: 'STRATEGY', ref: 'str-vol-target', label: 'Vol target strategy' },
        {
          id: 'N-2',
          kind: 'DEPLOYMENT',
          ref: 'dep-vol-halted',
          label: 'Vol target (kill-switched)',
        },
      ],
      edges: [{ from: 'N-1', to: 'N-2' }],
    },
    audit: [
      {
        id: 'AUD-8',
        kind: 'KILL_SWITCH',
        actor: 'Erin Risk',
        action: 'Kill switch engaged',
        detail: 'Limit breach.',
        occurredAt: '2026-07-25T14:15:00.000Z',
      },
      {
        id: 'AUD-9',
        kind: 'RUNTIME',
        actor: 'Trading Ops',
        action: 'Stopped',
        detail: 'Post-halt shutdown.',
        occurredAt: '2026-07-25T15:00:00.000Z',
      },
    ],
    versions: [
      {
        version: '0.4.0',
        stage: 'STOPPED',
        createdAt: '2026-07-25T00:00:00.000Z',
        note: 'Halted then stopped.',
        manifestHash: 'sha256:depvol04',
      },
    ],
    snapshots: [
      {
        deploymentId: 'DEP-VOL-HALTED',
        version: '0.4.0',
        stage: 'STOPPED',
        capturedAt: '2026-07-25T15:00:00.000Z',
        manifestHash: 'sha256:depvol04',
      },
    ],
    owner: { owner: 'Erin Risk', team: 'Volatility Trading', steward: 'Trading Guild' },
    tags: ['volatility', 'halted', 'kill-switch'],
    metadata: [{ key: 'mode', value: 'live' }],
    strategyRef: 'str-vol-target',
    registryRef: 'REG-dep-vol-halted',
    registeredAt: '2026-07-23T00:00:00.000Z',
    updatedAt: '2026-07-25T15:00:00.000Z',
  },
];

export const FAMILIES: readonly DeploymentFamily[] = [
  {
    namespace: 'equities',
    family: 'market-neutral',
    description: 'Market-neutral equity deployments.',
    deploymentCount: 1,
  },
  {
    namespace: 'equities',
    family: 'volatility',
    description: 'Volatility-target deployments.',
    deploymentCount: 1,
  },
  {
    namespace: 'crypto',
    family: 'momentum',
    description: 'Crypto momentum deployments.',
    deploymentCount: 1,
  },
  {
    namespace: 'multi-asset',
    family: 'risk-balanced',
    description: 'Risk-balanced multi-asset deployments.',
    deploymentCount: 1,
  },
  { namespace: 'fx', family: 'carry', description: 'FX carry deployments.', deploymentCount: 1 },
];
