/**
 * Synthetic in-memory seed for development and tests. Risk-governance METADATA ONLY —
 * NO VaR, NO CVaR, NO expected shortfall, NO stress testing, NO exposure calculation,
 * no persistence. Portfolios/backtests/signals/strategies are referenced by ref so
 * cross-links resolve; exposure values, limit bounds and metric VALUES are inert
 * strings, nothing is computed.
 */
import type { RiskAssessment, RiskComparison, RiskFamily, RiskPolicy } from '@platform/risk-sdk';

export const POLICIES: readonly RiskPolicy[] = [
  {
    id: 'POL-EXP',
    ref: 'pol-exposure',
    name: 'Exposure policy',
    category: 'EXPOSURE',
    version: '3.1.0',
    status: 'COMPLIANT',
    description: 'Gross/net exposure envelopes by mandate.',
  },
  {
    id: 'POL-CONC',
    ref: 'pol-concentration',
    name: 'Concentration policy',
    category: 'CONCENTRATION',
    version: '2.4.0',
    status: 'COMPLIANT',
    description: 'Single-name and sector concentration caps.',
  },
  {
    id: 'POL-LEV',
    ref: 'pol-leverage',
    name: 'Leverage policy',
    category: 'LEVERAGE',
    version: '1.9.0',
    status: 'WARNING',
    description: 'Gross leverage ceilings by strategy class.',
  },
  {
    id: 'POL-LIQ',
    ref: 'pol-liquidity',
    name: 'Liquidity policy',
    category: 'LIQUIDITY',
    version: '1.2.0',
    status: 'COMPLIANT',
    description: 'Minimum liquidity and days-to-liquidate.',
  },
  {
    id: 'POL-MAN',
    ref: 'pol-mandate',
    name: 'Mandate compliance',
    category: 'MANDATE',
    version: '4.0.0',
    status: 'COMPLIANT',
    description: 'Investment mandate and prohibited-instrument rules.',
  },
];

export const ASSESSMENTS: readonly RiskAssessment[] = [
  {
    id: 'RA-EQUITY-MN',
    slug: 'equity-market-neutral-risk',
    name: 'Equity market-neutral risk',
    description:
      'Execution-authorized risk assessment for the published equity market-neutral portfolio.',
    namespace: 'equities',
    family: 'market-neutral',
    stage: 'EXECUTION_AUTHORIZED',
    decision: 'CLEARED',
    version: '2.0.0',
    subjectKind: 'PORTFOLIO',
    subjectRef: 'pf-equity-mn',
    subjectName: 'Equity market-neutral',
    policies: [
      {
        id: 'POL-EXP',
        ref: 'pol-exposure',
        name: 'Exposure policy',
        category: 'EXPOSURE',
        version: '3.1.0',
        status: 'COMPLIANT',
        description: 'Gross/net exposure envelopes.',
      },
      {
        id: 'POL-CONC',
        ref: 'pol-concentration',
        name: 'Concentration policy',
        category: 'CONCENTRATION',
        version: '2.4.0',
        status: 'COMPLIANT',
        description: 'Single-name and sector caps.',
      },
    ],
    rules: [
      {
        id: 'RUL-1',
        policyRef: 'pol-exposure',
        code: 'EXP-NET',
        label: 'Net exposure within band',
        expression: '|net| ≤ 2%',
        status: 'COMPLIANT',
        severity: 'high',
      },
      {
        id: 'RUL-2',
        policyRef: 'pol-concentration',
        code: 'CONC-NAME',
        label: 'Max name weight',
        expression: 'name ≤ 3%',
        status: 'COMPLIANT',
        severity: 'medium',
      },
    ],
    limits: [
      {
        id: 'LIM-1',
        scope: 'PORTFOLIO',
        label: 'Gross exposure',
        bound: '≤ 200%',
        utilization: '198%',
        status: 'WARNING',
      },
      {
        id: 'LIM-2',
        scope: 'SECTOR',
        label: 'Sector exposure',
        bound: '≤ 25%',
        utilization: '18%',
        status: 'WITHIN',
      },
    ],
    constraints: [
      { id: 'RCON-1', label: 'Dollar neutral', bound: '|net| ≤ 2%', status: 'COMPLIANT' },
    ],
    exposures: [
      {
        id: 'EXP-1',
        dimension: 'ASSET_CLASS',
        label: 'Equity',
        value: '198%',
        limit: '≤ 200%',
        status: 'WARNING',
      },
      {
        id: 'EXP-2',
        dimension: 'SECTOR',
        label: 'Technology',
        value: '18%',
        limit: '≤ 25%',
        status: 'WITHIN',
      },
      {
        id: 'EXP-3',
        dimension: 'CURRENCY',
        label: 'USD',
        value: '100%',
        limit: '≤ 100%',
        status: 'WITHIN',
      },
    ],
    metrics: [
      { key: 'gross_exposure', value: '198%' },
      { key: 'net_exposure', value: '1.2%' },
      { key: 'leverage', value: '2.0x' },
      { key: 'concentration', value: '0.041' },
      { key: 'largest_position', value: '2.4%' },
      { key: 'limit_utilization', value: '99%' },
      { key: 'open_exceptions', value: '0' },
      { key: 'active_overrides', value: '0' },
    ],
    validation: {
      status: 'PASSED',
      method: 'Policy + limit validation',
      checkedAt: '2026-07-21T00:00:00.000Z',
      note: 'Policies compliant; limits within envelope.',
    },
    approval: 'APPROVED',
    reviews: [
      {
        id: 'RRV-1',
        reviewer: 'Risk Committee',
        stage: 'EXCEPTION_REVIEW',
        status: 'PASSED',
        reviewedAt: '2026-07-21T12:00:00.000Z',
      },
    ],
    approvals: [
      {
        id: 'RAP-1',
        role: 'Chief Risk Officer',
        status: 'APPROVED',
        decidedAt: '2026-07-22T00:00:00.000Z',
        rationale: 'Within all limits; execution authorized.',
        counterSignedBy: 'Head of Risk',
      },
    ],
    exceptions: [],
    overrides: [],
    reports: [
      {
        id: 'RPT-1',
        kind: 'RISK_SUMMARY',
        title: 'Risk summary',
        ref: 'rep-risk-equity-mn',
        generatedAt: '2026-07-22T01:00:00.000Z',
        summary: 'Cleared for execution.',
      },
    ],
    audit: [
      {
        id: 'AUD-1',
        kind: 'ASSESSMENT',
        actor: 'Ada Risk',
        action: 'Requested assessment',
        detail: 'Assessment requested.',
        occurredAt: '2026-07-20T00:00:00.000Z',
      },
      {
        id: 'AUD-2',
        kind: 'APPROVAL',
        actor: 'Chief Risk Officer',
        action: 'Approved',
        detail: 'Execution authorized.',
        occurredAt: '2026-07-22T00:00:00.000Z',
      },
    ],
    dependencies: [
      {
        id: 'RDEP-1',
        kind: 'PORTFOLIO',
        ref: 'pf-equity-mn',
        name: 'Equity market-neutral',
        status: 'SATISFIED',
      },
      {
        id: 'RDEP-2',
        kind: 'BACKTEST',
        ref: 'bt-reversal',
        name: 'Reversal L/S historical',
        status: 'SATISFIED',
      },
    ],
    lineage: {
      nodes: [
        { id: 'N-1', kind: 'PORTFOLIO', ref: 'pf-equity-mn', label: 'Equity market-neutral' },
        { id: 'N-2', kind: 'BACKTEST', ref: 'bt-reversal', label: 'Reversal L/S historical' },
        { id: 'N-3', kind: 'ASSESSMENT', ref: 'ra-equity-mn', label: 'Equity market-neutral risk' },
      ],
      edges: [
        { from: 'N-1', to: 'N-3' },
        { from: 'N-2', to: 'N-1' },
      ],
    },
    versions: [
      {
        version: '2.0.0',
        stage: 'EXECUTION_AUTHORIZED',
        createdAt: '2026-07-22T00:00:00.000Z',
        note: 'Authorized.',
        manifestHash: 'sha256:ra20',
      },
      {
        version: '1.0.0',
        stage: 'ARCHIVED',
        createdAt: '2026-06-01T00:00:00.000Z',
        note: 'Prior cycle.',
        manifestHash: 'sha256:ra10',
      },
    ],
    snapshots: [
      {
        assessmentId: 'RA-EQUITY-MN',
        version: '2.0.0',
        stage: 'EXECUTION_AUTHORIZED',
        decision: 'CLEARED',
        capturedAt: '2026-07-22T00:00:00.000Z',
        manifestHash: 'sha256:ra20',
      },
    ],
    owner: { owner: 'Ada Risk', team: 'Risk Management', steward: 'Risk Guild' },
    tags: ['market-neutral', 'equity', 'cleared'],
    metadata: [{ key: 'mandate', value: 'US market-neutral' }],
    portfolioRef: 'pf-equity-mn',
    backtestRef: 'bt-reversal',
    registryRef: 'REG-ra-equity-mn',
    registeredAt: '2026-07-20T00:00:00.000Z',
    updatedAt: '2026-07-22T00:00:00.000Z',
  },
  {
    id: 'RA-MULTI-ASSET',
    slug: 'multi-asset-risk',
    name: 'Multi-asset risk-balanced risk',
    description:
      'Risk assessment for the risk-balanced multi-asset portfolio awaiting governance approval.',
    namespace: 'multi-asset',
    family: 'risk-balanced',
    stage: 'APPROVAL',
    decision: 'PENDING',
    version: '1.1.0',
    subjectKind: 'PORTFOLIO',
    subjectRef: 'pf-multi-asset',
    subjectName: 'Multi-asset risk-balanced',
    policies: [
      {
        id: 'POL-LEV',
        ref: 'pol-leverage',
        name: 'Leverage policy',
        category: 'LEVERAGE',
        version: '1.9.0',
        status: 'WARNING',
        description: 'Gross leverage ceilings.',
      },
      {
        id: 'POL-CONC',
        ref: 'pol-concentration',
        name: 'Concentration policy',
        category: 'CONCENTRATION',
        version: '2.4.0',
        status: 'COMPLIANT',
        description: 'Sleeve concentration.',
      },
    ],
    rules: [
      {
        id: 'RUL-3',
        policyRef: 'pol-leverage',
        code: 'LEV-GROSS',
        label: 'Gross leverage ceiling',
        expression: 'gross ≤ 1.5x',
        status: 'WARNING',
        severity: 'medium',
      },
      {
        id: 'RUL-4',
        policyRef: 'pol-concentration',
        code: 'CONC-SLEEVE',
        label: 'Sleeve concentration',
        expression: 'sleeve ≤ 40%',
        status: 'COMPLIANT',
        severity: 'medium',
      },
    ],
    limits: [
      {
        id: 'LIM-3',
        scope: 'PORTFOLIO',
        label: 'Gross leverage',
        bound: '≤ 1.5x',
        utilization: '1.4x',
        status: 'WARNING',
      },
      {
        id: 'LIM-4',
        scope: 'ASSET_CLASS',
        label: 'Rates sleeve',
        bound: '≤ 40%',
        utilization: '34%',
        status: 'WITHIN',
      },
    ],
    constraints: [
      { id: 'RCON-2', label: 'Equal risk contribution', bound: 'ERC', status: 'COMPLIANT' },
    ],
    exposures: [
      {
        id: 'EXP-4',
        dimension: 'ASSET_CLASS',
        label: 'Rates',
        value: '34%',
        limit: '≤ 40%',
        status: 'WITHIN',
      },
      {
        id: 'EXP-5',
        dimension: 'ASSET_CLASS',
        label: 'Equity',
        value: '28%',
        limit: '≤ 40%',
        status: 'WITHIN',
      },
      {
        id: 'EXP-6',
        dimension: 'REGION',
        label: 'Global',
        value: '100%',
        limit: '≤ 100%',
        status: 'WITHIN',
      },
    ],
    metrics: [
      { key: 'gross_exposure', value: '100%' },
      { key: 'net_exposure', value: '84%' },
      { key: 'leverage', value: '1.4x' },
      { key: 'concentration', value: '0.088' },
      { key: 'largest_position', value: '34%' },
      { key: 'limit_utilization', value: '93%' },
      { key: 'open_exceptions', value: '0' },
      { key: 'active_overrides', value: '0' },
    ],
    validation: {
      status: 'PASSED',
      method: 'Policy + limit validation',
      checkedAt: '2026-07-28T06:30:00.000Z',
      note: 'Leverage near ceiling (warning).',
    },
    approval: 'PENDING',
    reviews: [
      {
        id: 'RRV-2',
        reviewer: 'Risk Committee',
        stage: 'EXCEPTION_REVIEW',
        status: 'PASSED',
        reviewedAt: '2026-07-29T00:00:00.000Z',
      },
    ],
    approvals: [{ id: 'RAP-2', role: 'Chief Risk Officer', status: 'PENDING' }],
    exceptions: [],
    overrides: [],
    reports: [
      {
        id: 'RPT-2',
        kind: 'EXPOSURE',
        title: 'Exposure report',
        ref: 'rep-risk-multi-asset',
        generatedAt: '2026-07-29T00:00:00.000Z',
        summary: 'Sleeve exposures within limits.',
      },
    ],
    audit: [
      {
        id: 'AUD-3',
        kind: 'ASSESSMENT',
        actor: 'Blaise Risk',
        action: 'Requested assessment',
        detail: 'Assessment requested.',
        occurredAt: '2026-07-27T00:00:00.000Z',
      },
      {
        id: 'AUD-4',
        kind: 'APPROVAL',
        actor: 'risk-engine',
        action: 'Requested approval',
        detail: 'Approval requested.',
        occurredAt: '2026-07-29T00:00:00.000Z',
      },
    ],
    dependencies: [
      {
        id: 'RDEP-3',
        kind: 'PORTFOLIO',
        ref: 'pf-multi-asset',
        name: 'Multi-asset risk-balanced',
        status: 'SATISFIED',
      },
      {
        id: 'RDEP-4',
        kind: 'STRATEGY',
        ref: 'str-fx-carry',
        name: 'FX carry strategy',
        status: 'SATISFIED',
      },
    ],
    lineage: {
      nodes: [
        { id: 'N-1', kind: 'PORTFOLIO', ref: 'pf-multi-asset', label: 'Multi-asset risk-balanced' },
        {
          id: 'N-2',
          kind: 'ASSESSMENT',
          ref: 'ra-multi-asset',
          label: 'Multi-asset risk-balanced risk',
        },
      ],
      edges: [{ from: 'N-1', to: 'N-2' }],
    },
    versions: [
      {
        version: '1.1.0',
        stage: 'APPROVAL',
        createdAt: '2026-07-29T00:00:00.000Z',
        note: 'Awaiting approval.',
        manifestHash: 'sha256:rama11',
      },
    ],
    snapshots: [
      {
        assessmentId: 'RA-MULTI-ASSET',
        version: '1.1.0',
        stage: 'APPROVAL',
        decision: 'PENDING',
        capturedAt: '2026-07-29T00:00:00.000Z',
        manifestHash: 'sha256:rama11',
      },
    ],
    owner: { owner: 'Blaise Risk', team: 'Risk Management', steward: 'Risk Guild' },
    tags: ['risk-balanced', 'multi-asset', 'approval'],
    metadata: [{ key: 'mandate', value: 'Global multi-asset' }],
    portfolioRef: 'pf-multi-asset',
    backtestRef: 'bt-carry-wf',
    registryRef: 'REG-ra-multi-asset',
    registeredAt: '2026-07-27T00:00:00.000Z',
    updatedAt: '2026-07-29T00:00:00.000Z',
  },
  {
    id: 'RA-CREDIT-CARRY',
    slug: 'credit-carry-risk',
    name: 'Credit carry risk',
    description:
      'Credit carry risk assessment in limit validation with a breached limit under override.',
    namespace: 'credit',
    family: 'carry',
    stage: 'LIMIT_VALIDATION',
    decision: 'CONDITIONAL',
    version: '0.5.0',
    subjectKind: 'PORTFOLIO',
    subjectRef: 'pf-credit-carry',
    subjectName: 'Credit carry',
    policies: [
      {
        id: 'POL-LIQ',
        ref: 'pol-liquidity',
        name: 'Liquidity policy',
        category: 'LIQUIDITY',
        version: '1.2.0',
        status: 'WARNING',
        description: 'Days-to-liquidate constraints.',
      },
      {
        id: 'POL-CONC',
        ref: 'pol-concentration',
        name: 'Concentration policy',
        category: 'CONCENTRATION',
        version: '2.4.0',
        status: 'BREACH',
        description: 'Sector concentration.',
      },
    ],
    rules: [
      {
        id: 'RUL-5',
        policyRef: 'pol-concentration',
        code: 'CONC-SECT',
        label: 'Sector concentration',
        expression: 'sector ≤ 25%',
        status: 'BREACH',
        severity: 'high',
      },
      {
        id: 'RUL-6',
        policyRef: 'pol-liquidity',
        code: 'LIQ-DAYS',
        label: 'Days-to-liquidate',
        expression: '≤ 5 days',
        status: 'WARNING',
        severity: 'medium',
      },
    ],
    limits: [
      {
        id: 'LIM-5',
        scope: 'SECTOR',
        label: 'Financials sector',
        bound: '≤ 25%',
        utilization: '31%',
        status: 'BREACHED',
      },
      {
        id: 'LIM-6',
        scope: 'PORTFOLIO',
        label: 'Gross exposure',
        bound: '≤ 100%',
        utilization: '96%',
        status: 'WITHIN',
      },
    ],
    constraints: [{ id: 'RCON-3', label: 'Min ADV', bound: '≥ $5m ADV', status: 'WARNING' }],
    exposures: [
      {
        id: 'EXP-7',
        dimension: 'SECTOR',
        label: 'Financials',
        value: '31%',
        limit: '≤ 25%',
        status: 'BREACHED',
      },
      {
        id: 'EXP-8',
        dimension: 'ASSET_CLASS',
        label: 'Credit',
        value: '96%',
        limit: '≤ 100%',
        status: 'WITHIN',
      },
    ],
    metrics: [
      { key: 'gross_exposure', value: '96%' },
      { key: 'net_exposure', value: '96%' },
      { key: 'leverage', value: '1.0x' },
      { key: 'concentration', value: '0.152' },
      { key: 'largest_position', value: '4.1%' },
      { key: 'limit_utilization', value: '124%' },
      { key: 'open_exceptions', value: '1' },
      { key: 'active_overrides', value: '1' },
    ],
    validation: {
      status: 'PENDING',
      method: 'Limit validation',
      note: 'Sector limit breach under review.',
    },
    approval: 'NOT_REQUESTED',
    reviews: [],
    approvals: [],
    exceptions: [
      {
        id: 'EXC-1',
        code: 'EXC-CONC',
        reason: 'Temporary sector overweight pending rebalance.',
        status: 'OPEN',
        raisedBy: 'Cleo Risk',
        raisedAt: '2026-08-02T00:00:00.000Z',
        expiresAt: '2026-08-09T00:00:00.000Z',
        ruleRef: 'CONC-SECT',
      },
    ],
    overrides: [
      {
        id: 'OVR-1',
        reason: 'Approved temporary overweight; rebalance scheduled.',
        status: 'ACTIVE',
        authorizedBy: 'Head of Risk',
        counterSignedBy: 'Chief Risk Officer',
        grantedAt: '2026-08-02T01:00:00.000Z',
        expiresAt: '2026-08-09T00:00:00.000Z',
      },
    ],
    reports: [
      {
        id: 'RPT-3',
        kind: 'LIMIT',
        title: 'Limit report',
        ref: 'rep-risk-credit-carry',
        generatedAt: '2026-08-02T00:00:00.000Z',
        summary: 'Financials sector limit breached.',
      },
    ],
    audit: [
      {
        id: 'AUD-5',
        kind: 'LIMIT',
        actor: 'risk-engine',
        action: 'Limit breach detected',
        detail: 'Financials 31% > 25%.',
        occurredAt: '2026-08-02T00:00:00.000Z',
      },
      {
        id: 'AUD-6',
        kind: 'EXCEPTION',
        actor: 'Cleo Risk',
        action: 'Raised exception',
        detail: 'Temporary overweight.',
        occurredAt: '2026-08-02T00:30:00.000Z',
      },
      {
        id: 'AUD-7',
        kind: 'OVERRIDE',
        actor: 'Head of Risk',
        action: 'Recorded override',
        detail: 'Counter-signed by CRO.',
        occurredAt: '2026-08-02T01:00:00.000Z',
      },
    ],
    dependencies: [
      {
        id: 'RDEP-5',
        kind: 'PORTFOLIO',
        ref: 'pf-credit-carry',
        name: 'Credit carry',
        status: 'SATISFIED',
      },
      {
        id: 'RDEP-6',
        kind: 'SIGNAL',
        ref: 'sig-fx-carry',
        name: 'Carry composite',
        status: 'SATISFIED',
      },
    ],
    lineage: {
      nodes: [
        { id: 'N-1', kind: 'SIGNAL', ref: 'sig-fx-carry', label: 'Carry composite' },
        { id: 'N-2', kind: 'PORTFOLIO', ref: 'pf-credit-carry', label: 'Credit carry' },
        { id: 'N-3', kind: 'ASSESSMENT', ref: 'ra-credit-carry', label: 'Credit carry risk' },
      ],
      edges: [
        { from: 'N-1', to: 'N-2' },
        { from: 'N-2', to: 'N-3' },
      ],
    },
    versions: [
      {
        version: '0.5.0',
        stage: 'LIMIT_VALIDATION',
        createdAt: '2026-08-02T00:00:00.000Z',
        note: 'Under limit validation.',
        manifestHash: 'sha256:racc05',
      },
    ],
    snapshots: [],
    owner: { owner: 'Cleo Risk', team: 'Credit Risk', steward: 'Risk Guild' },
    tags: ['carry', 'credit', 'breach'],
    metadata: [{ key: 'mandate', value: 'IG credit' }],
    portfolioRef: 'pf-credit-carry',
    registryRef: 'REG-ra-credit-carry',
    registeredAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-02T00:00:00.000Z',
  },
  {
    id: 'RA-FX-MOM',
    slug: 'fx-momentum-risk',
    name: 'FX momentum risk',
    description: 'FX momentum risk assessment in policy validation.',
    namespace: 'fx',
    family: 'momentum',
    stage: 'POLICY_VALIDATION',
    decision: 'PENDING',
    version: '0.1.0',
    subjectKind: 'PORTFOLIO',
    subjectRef: 'pf-fx-mom-draft',
    subjectName: 'FX momentum draft',
    policies: [
      {
        id: 'POL-EXP',
        ref: 'pol-exposure',
        name: 'Exposure policy',
        category: 'EXPOSURE',
        version: '3.1.0',
        status: 'NOT_EVALUATED',
        description: 'Exposure envelopes.',
      },
    ],
    rules: [
      {
        id: 'RUL-7',
        policyRef: 'pol-exposure',
        code: 'EXP-PAIR',
        label: 'Max pair weight',
        expression: 'pair ≤ 15%',
        status: 'NOT_EVALUATED',
        severity: 'medium',
      },
    ],
    limits: [
      {
        id: 'LIM-7',
        scope: 'INSTRUMENT',
        label: 'Max pair weight',
        bound: '≤ 15%',
        utilization: '—',
        status: 'NOT_EVALUATED',
      },
    ],
    constraints: [
      { id: 'RCON-4', label: 'Max pair weight', bound: '≤ 15%', status: 'NOT_EVALUATED' },
    ],
    exposures: [
      {
        id: 'EXP-9',
        dimension: 'CURRENCY',
        label: 'G10 FX',
        value: '—',
        limit: '≤ 15% per pair',
        status: 'NOT_EVALUATED',
      },
    ],
    metrics: [
      { key: 'open_exceptions', value: '0' },
      { key: 'active_overrides', value: '0' },
    ],
    validation: {
      status: 'PENDING',
      method: 'Policy validation',
      note: 'Policy validation in progress.',
    },
    approval: 'NOT_REQUESTED',
    reviews: [],
    approvals: [],
    exceptions: [],
    overrides: [],
    reports: [],
    audit: [
      {
        id: 'AUD-8',
        kind: 'POLICY',
        actor: 'risk-engine',
        action: 'Requested policy validation',
        detail: 'Policy validation requested.',
        occurredAt: '2026-08-02T00:00:00.000Z',
      },
    ],
    dependencies: [
      {
        id: 'RDEP-7',
        kind: 'PORTFOLIO',
        ref: 'pf-fx-mom-draft',
        name: 'FX momentum draft',
        status: 'PENDING',
      },
    ],
    lineage: {
      nodes: [
        { id: 'N-1', kind: 'PORTFOLIO', ref: 'pf-fx-mom-draft', label: 'FX momentum draft' },
        { id: 'N-2', kind: 'ASSESSMENT', ref: 'ra-fx-mom', label: 'FX momentum risk' },
      ],
      edges: [{ from: 'N-1', to: 'N-2' }],
    },
    versions: [
      {
        version: '0.1.0',
        stage: 'POLICY_VALIDATION',
        createdAt: '2026-08-02T00:00:00.000Z',
        note: 'Policy validation.',
        manifestHash: 'sha256:rafx01',
      },
    ],
    snapshots: [],
    owner: { owner: 'Dara Risk', team: 'Macro Risk', steward: 'Risk Guild' },
    tags: ['momentum', 'fx', 'validation'],
    metadata: [{ key: 'mandate', value: 'G10 FX' }],
    portfolioRef: 'pf-fx-mom-draft',
    registryRef: 'REG-ra-fx-mom',
    registeredAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-02T00:00:00.000Z',
  },
  {
    id: 'RA-VOL-BLOCKED',
    slug: 'vol-target-risk',
    name: 'Vol target risk (blocked)',
    description:
      'Volatility-target risk assessment blocked in exception review after a policy breach.',
    namespace: 'equities',
    family: 'volatility',
    stage: 'EXCEPTION_REVIEW',
    decision: 'BLOCKED',
    version: '0.3.0',
    subjectKind: 'PORTFOLIO',
    subjectRef: 'pf-vol-cancelled',
    subjectName: 'Vol target (cancelled)',
    policies: [
      {
        id: 'POL-MAN',
        ref: 'pol-mandate',
        name: 'Mandate compliance',
        category: 'MANDATE',
        version: '4.0.0',
        status: 'BREACH',
        description: 'Prohibited-instrument rule.',
      },
    ],
    rules: [
      {
        id: 'RUL-8',
        policyRef: 'pol-mandate',
        code: 'MAN-PROHIB',
        label: 'Prohibited instrument',
        expression: 'no uncleared OTC',
        status: 'BREACH',
        severity: 'critical',
      },
    ],
    limits: [
      {
        id: 'LIM-8',
        scope: 'INSTRUMENT',
        label: 'Uncleared OTC',
        bound: '= 0',
        utilization: '2 positions',
        status: 'BREACHED',
      },
    ],
    constraints: [
      { id: 'RCON-5', label: 'Vol target', bound: '10% annualized', status: 'NOT_EVALUATED' },
    ],
    exposures: [
      {
        id: 'EXP-10',
        dimension: 'ASSET_CLASS',
        label: 'Uncleared OTC',
        value: '2 positions',
        limit: '= 0',
        status: 'BREACHED',
      },
    ],
    metrics: [
      { key: 'gross_exposure', value: '—' },
      { key: 'limit_utilization', value: '—' },
      { key: 'open_exceptions', value: '1' },
      { key: 'active_overrides', value: '0' },
    ],
    validation: {
      status: 'FAILED',
      method: 'Policy validation',
      checkedAt: '2026-07-26T00:00:00.000Z',
      note: 'Mandate breach — prohibited instruments.',
    },
    approval: 'NOT_REQUESTED',
    reviews: [
      {
        id: 'RRV-3',
        reviewer: 'Risk Committee',
        stage: 'EXCEPTION_REVIEW',
        status: 'CHANGES_REQUESTED',
        note: 'Remove prohibited positions before resubmission.',
      },
    ],
    approvals: [],
    exceptions: [
      {
        id: 'EXC-2',
        code: 'EXC-MAN',
        reason: 'Prohibited-instrument breach; blocking.',
        status: 'OPEN',
        raisedBy: 'Dara Risk',
        raisedAt: '2026-07-26T00:30:00.000Z',
        ruleRef: 'MAN-PROHIB',
      },
    ],
    overrides: [],
    reports: [
      {
        id: 'RPT-4',
        kind: 'EXCEPTION',
        title: 'Exception report',
        ref: 'rep-risk-vol',
        generatedAt: '2026-07-26T01:00:00.000Z',
        summary: 'Mandate breach — blocked.',
      },
    ],
    audit: [
      {
        id: 'AUD-9',
        kind: 'POLICY',
        actor: 'risk-engine',
        action: 'Policy breach detected',
        detail: 'Prohibited instruments present.',
        occurredAt: '2026-07-26T00:00:00.000Z',
      },
      {
        id: 'AUD-10',
        kind: 'EXCEPTION',
        actor: 'Dara Risk',
        action: 'Raised blocking exception',
        detail: 'Mandate breach.',
        occurredAt: '2026-07-26T00:30:00.000Z',
      },
    ],
    dependencies: [
      {
        id: 'RDEP-8',
        kind: 'PORTFOLIO',
        ref: 'pf-vol-cancelled',
        name: 'Vol target (cancelled)',
        status: 'MISSING',
      },
    ],
    lineage: {
      nodes: [
        { id: 'N-1', kind: 'PORTFOLIO', ref: 'pf-vol-cancelled', label: 'Vol target (cancelled)' },
        {
          id: 'N-2',
          kind: 'ASSESSMENT',
          ref: 'ra-vol-blocked',
          label: 'Vol target risk (blocked)',
        },
      ],
      edges: [{ from: 'N-1', to: 'N-2' }],
    },
    versions: [
      {
        version: '0.3.0',
        stage: 'EXCEPTION_REVIEW',
        createdAt: '2026-07-26T00:00:00.000Z',
        note: 'Blocked in exception review.',
        manifestHash: 'sha256:ravol03',
      },
    ],
    snapshots: [],
    owner: { owner: 'Dara Risk', team: 'Volatility Risk', steward: 'Risk Guild' },
    tags: ['volatility', 'blocked', 'breach'],
    metadata: [{ key: 'mandate', value: 'US options' }],
    portfolioRef: 'pf-vol-cancelled',
    registryRef: 'REG-ra-vol-blocked',
    registeredAt: '2026-07-25T00:00:00.000Z',
    updatedAt: '2026-07-26T01:00:00.000Z',
  },
];

export const FAMILIES: readonly RiskFamily[] = [
  {
    namespace: 'equities',
    family: 'market-neutral',
    description: 'Market-neutral equity risk assessments.',
    assessmentCount: 1,
  },
  {
    namespace: 'equities',
    family: 'volatility',
    description: 'Volatility-target risk assessments.',
    assessmentCount: 1,
  },
  {
    namespace: 'multi-asset',
    family: 'risk-balanced',
    description: 'Risk-balanced multi-asset assessments.',
    assessmentCount: 1,
  },
  {
    namespace: 'credit',
    family: 'carry',
    description: 'Credit carry risk assessments.',
    assessmentCount: 1,
  },
  {
    namespace: 'fx',
    family: 'momentum',
    description: 'FX momentum risk assessments.',
    assessmentCount: 1,
  },
];

export const COMPARISONS: readonly RiskComparison[] = [
  {
    id: 'RCMP-1',
    name: 'Market-neutral vs risk-balanced (risk)',
    assessmentIds: ['RA-EQUITY-MN', 'RA-MULTI-ASSET'],
    metricKeys: [
      'gross_exposure',
      'net_exposure',
      'leverage',
      'limit_utilization',
      'open_exceptions',
    ],
    createdAt: '2026-07-29T00:00:00.000Z',
    note: 'Head-to-head of the two constructed portfolios’ risk.',
  },
];
