/**
 * Live Trading Platform DTOs. The canonical shapes are owned by the shared
 * `@platform/trading-sdk` (single source of truth across the service and this UI); this
 * module re-exports them so both tiers speak the same vocabulary. Inert data only — no
 * exchange/broker SDK, no API keys, no HTTP/WebSocket/FIX, no order execution.
 */
export type {
  AccountBalance,
  ApprovalStatus,
  AuditKind,
  AuthorizationToken,
  BrokerConnection,
  BrokerKind,
  ConnectionStatus,
  DependencyKind,
  DependencyStatus,
  Deployment,
  DeploymentDependency,
  DeploymentFamily,
  DeploymentLineage,
  DeploymentSnapshot,
  DeploymentStage,
  DeploymentValidation,
  DeploymentVersion,
  EmergencyAction,
  EmergencyKind,
  ExchangeConnection,
  ExecutionMode,
  HealthStatus,
  KillSwitch,
  KillSwitchStatus,
  LineageNode,
  LineageNodeKind,
  MetadataEntry,
  MetricDescriptor,
  MetricKey,
  OrderSide,
  OrderStatus,
  OrderType,
  PositionSide,
  ProviderDescriptor,
  ProviderId,
  RuntimeStatus,
  RunningStrategy,
  TimelineKind,
  TradingAccount,
  TradingApproval,
  TradingAudit,
  TradingHealth,
  TradingMetric,
  TradingOrder,
  TradingOwner,
  TradingPermission,
  TradingPortfolio,
  TradingPosition,
  TradingSession,
  TradingTimelineEvent,
  ValidationStatus,
} from '@platform/trading-sdk';
