/**
 * Risk Engine DTOs. The canonical shapes are owned by the shared `@platform/risk-sdk`
 * (single source of truth across the service and this UI); this module re-exports them
 * so both tiers speak the same vocabulary. Inert data only — no VaR, no CVaR, no
 * exposure calculation.
 */
export type {
  ApprovalStatus,
  AuditKind,
  DependencyKind,
  DependencyStatus,
  ExceptionStatus,
  ExposureDimension,
  LimitScope,
  LimitStatus,
  LineageNode,
  LineageNodeKind,
  MetadataEntry,
  MetricDescriptor,
  MetricKey,
  OverrideStatus,
  PolicyCategory,
  ReportKind,
  ReviewStatus,
  RiskApproval,
  RiskAssessment,
  RiskAudit,
  RiskComparison,
  RiskConstraint,
  RiskDecision,
  RiskDependency,
  RiskException,
  RiskExposure,
  RiskFamily,
  RiskLimit,
  RiskLineage,
  RiskMetric,
  RiskOverride,
  RiskOwner,
  RiskPolicy,
  RiskReport,
  RiskReview,
  RiskRule,
  RiskSnapshot,
  RiskStage,
  RiskValidation,
  RiskVersion,
  RuleStatus,
  SubjectKind,
  ValidationStatus,
} from '@platform/risk-sdk';
