/**
 * Synthetic in-memory seed for development and tests. Simulation METADATA ONLY — NO
 * execution algorithm, NO exchange/broker connectivity, NO FIX, NO WebSocket, NO
 * fill/price/PnL computation, no persistence. Portfolios/strategies/backtests are
 * referenced by ref so cross-links resolve; quantities, prices, exposures and metric
 * VALUES are inert strings, nothing is computed or transmitted.
 */
import type {
  SimulationSession,
  SimulationComparison,
  SimulationFamily,
  ScenarioTemplate,
} from '@platform/execution-sdk';

export const SESSIONS: readonly SimulationSession[] = [
  {
    id: 'SIM-EQUITY-MN',
    slug: 'equity-market-neutral-sim',
    name: 'Equity market-neutral sim',
    description: 'Approved paper-trading simulation of the equity market-neutral portfolio.',
    namespace: 'equities',
    family: 'market-neutral',
    stage: 'APPROVED',
    version: '2.0.0',
    templateRef: 'TPL-EQUITY-DAILY',
    scenario: {
      id: 'SCN-1',
      label: 'Daily rebalance 2025',
      universe: 'US large-cap',
      startDate: '2025-01-01',
      endDate: '2025-12-31',
      fillModel: 'participation-aware',
      venueModel: 'consolidated',
      latencyModel: 'fixed-50ms',
      parameters: [
        { key: 'participation', value: '10%' },
        { key: 'schedule', value: 'daily-close' },
      ],
      notes: 'Net-of-cost paper trading.',
    },
    run: {
      id: 'RUN-3',
      status: 'COMPLETED',
      attempt: 1,
      progress: 100,
      startedAt: '2026-07-20T00:00:00.000Z',
      endedAt: '2026-07-20T02:00:00.000Z',
      note: 'Completed nominally.',
    },
    runs: [
      {
        id: 'RUN-3',
        status: 'COMPLETED',
        attempt: 1,
        progress: 100,
        startedAt: '2026-07-20T00:00:00.000Z',
        endedAt: '2026-07-20T02:00:00.000Z',
        note: 'Completed nominally.',
      },
    ],
    orders: [
      {
        id: 'ORD-1',
        clientOrderId: 'C-1001',
        symbol: 'AAPL',
        side: 'BUY',
        type: 'LIMIT',
        quantity: '1200',
        limitPrice: '188.50',
        filledQuantity: '1200',
        status: 'FILLED',
        createdAt: '2026-07-20T00:05:00.000Z',
      },
      {
        id: 'ORD-2',
        clientOrderId: 'C-1002',
        symbol: 'XYZ',
        side: 'SELL',
        type: 'MARKET',
        quantity: '900',
        filledQuantity: '900',
        status: 'FILLED',
        createdAt: '2026-07-20T00:06:00.000Z',
      },
      {
        id: 'ORD-3',
        clientOrderId: 'C-1003',
        symbol: 'MSFT',
        side: 'BUY',
        type: 'LIMIT',
        quantity: '800',
        limitPrice: '410.00',
        filledQuantity: '500',
        status: 'PARTIALLY_FILLED',
        createdAt: '2026-07-20T00:07:00.000Z',
      },
    ],
    fills: [
      {
        id: 'FIL-1',
        orderId: 'ORD-1',
        symbol: 'AAPL',
        side: 'BUY',
        quantity: '1200',
        price: '188.42',
        liquidity: 'TAKER',
        venue: 'SIM-A',
        filledAt: '2026-07-20T00:05:02.000Z',
      },
      {
        id: 'FIL-2',
        orderId: 'ORD-2',
        symbol: 'XYZ',
        side: 'SELL',
        quantity: '900',
        price: '54.10',
        liquidity: 'MAKER',
        venue: 'SIM-A',
        filledAt: '2026-07-20T00:06:01.000Z',
      },
      {
        id: 'FIL-3',
        orderId: 'ORD-3',
        symbol: 'MSFT',
        side: 'BUY',
        quantity: '500',
        price: '409.90',
        liquidity: 'TAKER',
        venue: 'SIM-B',
        filledAt: '2026-07-20T00:07:03.000Z',
      },
    ],
    positions: [
      {
        id: 'POS-1',
        symbol: 'AAPL',
        side: 'LONG',
        quantity: '1200',
        averagePrice: '188.42',
        marketValue: '226104',
      },
      {
        id: 'POS-2',
        symbol: 'XYZ',
        side: 'SHORT',
        quantity: '900',
        averagePrice: '54.10',
        marketValue: '-48690',
      },
      {
        id: 'POS-3',
        symbol: 'MSFT',
        side: 'LONG',
        quantity: '500',
        averagePrice: '409.90',
        marketValue: '204950',
      },
    ],
    portfolio: {
      baseCurrency: 'USD',
      cash: '617636',
      equity: '1000000',
      grossExposure: '479744',
      netExposure: '382364',
      realizedPnl: '0',
      unrealizedPnl: '1240',
    },
    timeline: [
      {
        id: 'TL-1',
        kind: 'SESSION',
        label: 'Session started',
        detail: 'Simulation started.',
        at: '2026-07-20T00:00:00.000Z',
      },
      {
        id: 'TL-2',
        kind: 'ORDER',
        label: 'Order filled',
        detail: 'AAPL 1200 @ 188.42.',
        at: '2026-07-20T00:05:02.000Z',
      },
      {
        id: 'TL-3',
        kind: 'FILL',
        label: 'Fill booked',
        detail: 'XYZ 900 @ 54.10.',
        at: '2026-07-20T00:06:01.000Z',
      },
      {
        id: 'TL-4',
        kind: 'SESSION',
        label: 'Session completed',
        detail: 'Simulation completed.',
        at: '2026-07-20T02:00:00.000Z',
      },
    ],
    replays: [
      {
        id: 'RPL-1',
        sourceSessionId: 'SIM-EQUITY-MN',
        status: 'COMPLETED',
        note: 'Deterministic replay matched.',
        createdAt: '2026-07-21T00:00:00.000Z',
      },
    ],
    metrics: [
      { key: 'order_count', value: '312' },
      { key: 'fill_count', value: '298' },
      { key: 'fill_rate', value: '95.5%' },
      { key: 'avg_slippage', value: '3.2bps' },
      { key: 'sim_latency', value: '50ms' },
      { key: 'reject_rate', value: '0.6%' },
      { key: 'turnover', value: '0.18x' },
      { key: 'participation', value: '9.2%' },
    ],
    validation: {
      status: 'PASSED',
      method: 'Point-in-time + config validation',
      checkedAt: '2026-07-19T12:00:00.000Z',
      note: 'PIT verified; scenario valid.',
    },
    approval: 'APPROVED',
    reviews: [
      {
        id: 'SRV-1',
        reviewer: 'Execution Review',
        stage: 'REVIEW',
        status: 'PASSED',
        reviewedAt: '2026-07-21T00:00:00.000Z',
      },
    ],
    approvals: [
      {
        id: 'SAP-1',
        role: 'Head of Execution',
        status: 'APPROVED',
        decidedAt: '2026-07-22T00:00:00.000Z',
        rationale: 'Fill quality acceptable in simulation.',
      },
    ],
    reports: [
      {
        id: 'SRP-1',
        kind: 'EXECUTION_SUMMARY',
        title: 'Execution summary',
        ref: 'rep-exec-equity-mn',
        generatedAt: '2026-07-20T03:00:00.000Z',
        summary: 'Simulated fill quality and slippage.',
      },
    ],
    artifacts: [
      { id: 'SART-1', kind: 'BLOTTER', ref: 'blot-equity-mn', name: 'Order blotter' },
      { id: 'SART-2', kind: 'FILLS', ref: 'fills-equity-mn', name: 'Fills export' },
      { id: 'SART-3', kind: 'MANIFEST', ref: 'man-equity-mn', name: 'Run manifest' },
    ],
    dependencies: [
      {
        id: 'SDEP-1',
        kind: 'PORTFOLIO',
        ref: 'pf-equity-mn',
        name: 'Equity market-neutral',
        status: 'SATISFIED',
      },
      {
        id: 'SDEP-2',
        kind: 'BACKTEST',
        ref: 'bt-reversal',
        name: 'Reversal L/S historical',
        status: 'SATISFIED',
      },
    ],
    lineage: {
      nodes: [
        { id: 'N-1', kind: 'PORTFOLIO', ref: 'pf-equity-mn', label: 'Equity market-neutral' },
        { id: 'N-2', kind: 'BACKTEST', ref: 'bt-reversal', label: 'Reversal L/S historical' },
        { id: 'N-3', kind: 'SIMULATION', ref: 'sim-equity-mn', label: 'Equity market-neutral sim' },
      ],
      edges: [
        { from: 'N-1', to: 'N-3' },
        { from: 'N-2', to: 'N-1' },
      ],
    },
    versions: [
      {
        version: '2.0.0',
        stage: 'APPROVED',
        createdAt: '2026-07-22T00:00:00.000Z',
        note: 'Approved.',
        manifestHash: 'sha256:sim20',
      },
      {
        version: '1.0.0',
        stage: 'ARCHIVED',
        createdAt: '2026-06-01T00:00:00.000Z',
        note: 'Prior run.',
        manifestHash: 'sha256:sim10',
      },
    ],
    snapshots: [
      {
        sessionId: 'SIM-EQUITY-MN',
        version: '2.0.0',
        stage: 'APPROVED',
        capturedAt: '2026-07-22T00:00:00.000Z',
        manifestHash: 'sha256:sim20',
      },
    ],
    owner: { owner: 'Ada Trader', team: 'Execution Research', steward: 'Execution Guild' },
    tags: ['market-neutral', 'equity', 'approved'],
    metadata: [
      { key: 'universe', value: 'US large-cap' },
      { key: 'mode', value: 'paper' },
    ],
    portfolioRef: 'pf-equity-mn',
    strategyRef: 'str-reversal-ls',
    backtestRef: 'bt-reversal',
    registryRef: 'REG-sim-equity-mn',
    registeredAt: '2026-06-01T00:00:00.000Z',
    updatedAt: '2026-07-22T00:00:00.000Z',
  },
  {
    id: 'SIM-MULTI-ASSET',
    slug: 'multi-asset-sim',
    name: 'Multi-asset risk-balanced sim',
    description:
      'Multi-asset paper-trading simulation under review and awaiting governance approval.',
    namespace: 'multi-asset',
    family: 'risk-balanced',
    stage: 'REVIEW',
    version: '1.1.0',
    templateRef: 'TPL-MULTI-ASSET',
    scenario: {
      id: 'SCN-2',
      label: 'Quarterly rebalance',
      universe: 'Global multi-asset',
      startDate: '2024-01-01',
      endDate: '2025-12-31',
      fillModel: 'spread + impact',
      venueModel: 'multi-venue',
      latencyModel: 'variable',
      parameters: [{ key: 'schedule', value: 'quarterly' }],
      notes: 'Sleeve-level simulation.',
    },
    run: {
      id: 'RUN-7',
      status: 'COMPLETED',
      attempt: 2,
      progress: 100,
      startedAt: '2026-07-28T00:00:00.000Z',
      endedAt: '2026-07-28T03:00:00.000Z',
      note: 'Retried after data refresh.',
    },
    runs: [
      {
        id: 'RUN-6',
        status: 'FAILED',
        attempt: 1,
        progress: 40,
        startedAt: '2026-07-27T00:00:00.000Z',
        endedAt: '2026-07-27T01:00:00.000Z',
        note: 'Data gap.',
      },
      {
        id: 'RUN-7',
        status: 'COMPLETED',
        attempt: 2,
        progress: 100,
        startedAt: '2026-07-28T00:00:00.000Z',
        endedAt: '2026-07-28T03:00:00.000Z',
        note: 'Retried after data refresh.',
      },
    ],
    orders: [
      {
        id: 'ORD-4',
        clientOrderId: 'C-2001',
        symbol: 'ES',
        side: 'BUY',
        type: 'MARKET',
        quantity: '40',
        filledQuantity: '40',
        status: 'FILLED',
        createdAt: '2026-07-28T00:10:00.000Z',
      },
      {
        id: 'ORD-5',
        clientOrderId: 'C-2002',
        symbol: 'ZN',
        side: 'BUY',
        type: 'LIMIT',
        quantity: '120',
        limitPrice: '111.20',
        filledQuantity: '0',
        status: 'REJECTED',
        createdAt: '2026-07-28T00:11:00.000Z',
      },
    ],
    fills: [
      {
        id: 'FIL-4',
        orderId: 'ORD-4',
        symbol: 'ES',
        side: 'BUY',
        quantity: '40',
        price: '5210.25',
        liquidity: 'TAKER',
        venue: 'SIM-C',
        filledAt: '2026-07-28T00:10:02.000Z',
      },
    ],
    positions: [
      {
        id: 'POS-4',
        symbol: 'ES',
        side: 'LONG',
        quantity: '40',
        averagePrice: '5210.25',
        marketValue: '10420500',
      },
    ],
    portfolio: {
      baseCurrency: 'USD',
      cash: '4200000',
      equity: '10000000',
      grossExposure: '8400000',
      netExposure: '8400000',
      realizedPnl: '0',
      unrealizedPnl: '-3200',
    },
    timeline: [
      {
        id: 'TL-5',
        kind: 'SESSION',
        label: 'Session started',
        detail: 'Simulation started.',
        at: '2026-07-28T00:00:00.000Z',
      },
      {
        id: 'TL-6',
        kind: 'ORDER',
        label: 'Order rejected',
        detail: 'ZN 120 rejected (limit).',
        at: '2026-07-28T00:11:01.000Z',
      },
    ],
    replays: [],
    metrics: [
      { key: 'order_count', value: '86' },
      { key: 'fill_count', value: '71' },
      { key: 'fill_rate', value: '82.6%' },
      { key: 'avg_slippage', value: '5.1bps' },
      { key: 'sim_latency', value: '120ms' },
      { key: 'reject_rate', value: '4.7%' },
      { key: 'turnover', value: '0.09x' },
      { key: 'participation', value: '6.4%' },
    ],
    validation: {
      status: 'PASSED',
      method: 'Point-in-time + config validation',
      checkedAt: '2026-07-28T02:30:00.000Z',
      note: 'Scenario valid.',
    },
    approval: 'PENDING',
    reviews: [
      {
        id: 'SRV-2',
        reviewer: 'Execution Review',
        stage: 'REVIEW',
        status: 'PASSED',
        reviewedAt: '2026-07-29T00:00:00.000Z',
      },
    ],
    approvals: [{ id: 'SAP-2', role: 'Head of Execution', status: 'PENDING' }],
    reports: [
      {
        id: 'SRP-2',
        kind: 'TCA',
        title: 'TCA report',
        ref: 'rep-exec-multi-asset',
        generatedAt: '2026-07-28T04:00:00.000Z',
        summary: 'Simulated transaction-cost analysis.',
      },
    ],
    artifacts: [{ id: 'SART-4', kind: 'BLOTTER', ref: 'blot-multi-asset', name: 'Order blotter' }],
    dependencies: [
      {
        id: 'SDEP-3',
        kind: 'PORTFOLIO',
        ref: 'pf-multi-asset',
        name: 'Multi-asset risk-balanced',
        status: 'SATISFIED',
      },
      {
        id: 'SDEP-4',
        kind: 'STRATEGY',
        ref: 'str-fx-carry',
        name: 'FX carry strategy',
        status: 'SATISFIED',
      },
    ],
    lineage: {
      nodes: [
        { id: 'N-1', kind: 'PORTFOLIO', ref: 'pf-multi-asset', label: 'Multi-asset risk-balanced' },
        {
          id: 'N-2',
          kind: 'SIMULATION',
          ref: 'sim-multi-asset',
          label: 'Multi-asset risk-balanced sim',
        },
      ],
      edges: [{ from: 'N-1', to: 'N-2' }],
    },
    versions: [
      {
        version: '1.1.0',
        stage: 'REVIEW',
        createdAt: '2026-07-28T04:00:00.000Z',
        note: 'Under review.',
        manifestHash: 'sha256:simma11',
      },
    ],
    snapshots: [
      {
        sessionId: 'SIM-MULTI-ASSET',
        version: '1.1.0',
        stage: 'REVIEW',
        capturedAt: '2026-07-28T04:00:00.000Z',
        manifestHash: 'sha256:simma11',
      },
    ],
    owner: { owner: 'Blaise Trader', team: 'Execution Research', steward: 'Execution Guild' },
    tags: ['risk-balanced', 'multi-asset', 'review'],
    metadata: [
      { key: 'universe', value: 'Global multi-asset' },
      { key: 'mode', value: 'paper' },
    ],
    portfolioRef: 'pf-multi-asset',
    strategyRef: 'str-fx-carry',
    backtestRef: 'bt-carry-wf',
    registryRef: 'REG-sim-multi-asset',
    registeredAt: '2026-07-27T00:00:00.000Z',
    updatedAt: '2026-07-29T00:00:00.000Z',
  },
  {
    id: 'SIM-CREDIT-CARRY',
    slug: 'credit-carry-sim',
    name: 'Credit carry sim',
    description: 'Credit carry paper-trading simulation currently running.',
    namespace: 'credit',
    family: 'carry',
    stage: 'RUNNING',
    version: '0.5.0',
    templateRef: 'TPL-EQUITY-DAILY',
    scenario: {
      id: 'SCN-3',
      label: 'Daily rebalance',
      universe: 'IG credit',
      startDate: '2024-01-01',
      endDate: '2025-12-31',
      fillModel: 'linear',
      venueModel: 'consolidated',
      latencyModel: 'fixed-100ms',
      parameters: [{ key: 'schedule', value: 'daily' }],
      notes: 'In-flight run.',
    },
    run: {
      id: 'RUN-9',
      status: 'RUNNING',
      attempt: 1,
      progress: 55,
      startedAt: '2026-08-02T00:00:00.000Z',
      note: 'Simulation in progress.',
    },
    runs: [
      {
        id: 'RUN-9',
        status: 'RUNNING',
        attempt: 1,
        progress: 55,
        startedAt: '2026-08-02T00:00:00.000Z',
        note: 'Simulation in progress.',
      },
    ],
    orders: [
      {
        id: 'ORD-6',
        clientOrderId: 'C-3001',
        symbol: 'LQD',
        side: 'BUY',
        type: 'LIMIT',
        quantity: '5000',
        limitPrice: '108.10',
        filledQuantity: '2500',
        status: 'PARTIALLY_FILLED',
        createdAt: '2026-08-02T00:05:00.000Z',
      },
    ],
    fills: [
      {
        id: 'FIL-5',
        orderId: 'ORD-6',
        symbol: 'LQD',
        side: 'BUY',
        quantity: '2500',
        price: '108.08',
        liquidity: 'MAKER',
        venue: 'SIM-A',
        filledAt: '2026-08-02T00:05:05.000Z',
      },
    ],
    positions: [
      {
        id: 'POS-5',
        symbol: 'LQD',
        side: 'LONG',
        quantity: '2500',
        averagePrice: '108.08',
        marketValue: '270200',
      },
    ],
    portfolio: {
      baseCurrency: 'USD',
      cash: '729800',
      equity: '1000000',
      grossExposure: '270200',
      netExposure: '270200',
      realizedPnl: '0',
      unrealizedPnl: '0',
    },
    timeline: [
      {
        id: 'TL-7',
        kind: 'SESSION',
        label: 'Session started',
        detail: 'Simulation started.',
        at: '2026-08-02T00:00:00.000Z',
      },
    ],
    replays: [],
    metrics: [],
    validation: {
      status: 'PASSED',
      method: 'Point-in-time',
      checkedAt: '2026-08-01T00:00:00.000Z',
      note: 'PIT verified.',
    },
    approval: 'NOT_REQUESTED',
    reviews: [],
    approvals: [],
    reports: [],
    artifacts: [{ id: 'SART-5', kind: 'MANIFEST', ref: 'man-credit-carry', name: 'Run manifest' }],
    dependencies: [
      {
        id: 'SDEP-5',
        kind: 'PORTFOLIO',
        ref: 'pf-credit-carry',
        name: 'Credit carry',
        status: 'SATISFIED',
      },
      {
        id: 'SDEP-6',
        kind: 'SIGNAL',
        ref: 'sig-fx-carry',
        name: 'Carry composite',
        status: 'SATISFIED',
      },
    ],
    lineage: {
      nodes: [
        { id: 'N-1', kind: 'SIGNAL', ref: 'sig-fx-carry', label: 'Carry composite' },
        { id: 'N-2', kind: 'PORTFOLIO', ref: 'pf-credit-carry', label: 'Credit carry' },
        { id: 'N-3', kind: 'SIMULATION', ref: 'sim-credit-carry', label: 'Credit carry sim' },
      ],
      edges: [
        { from: 'N-1', to: 'N-2' },
        { from: 'N-2', to: 'N-3' },
      ],
    },
    versions: [
      {
        version: '0.5.0',
        stage: 'RUNNING',
        createdAt: '2026-08-02T00:00:00.000Z',
        note: 'Running.',
        manifestHash: 'sha256:simcc05',
      },
    ],
    snapshots: [],
    owner: { owner: 'Cleo Trader', team: 'Credit Execution', steward: 'Execution Guild' },
    tags: ['carry', 'credit', 'running'],
    metadata: [
      { key: 'universe', value: 'IG credit' },
      { key: 'mode', value: 'paper' },
    ],
    portfolioRef: 'pf-credit-carry',
    registryRef: 'REG-sim-credit-carry',
    registeredAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-02T00:00:00.000Z',
  },
  {
    id: 'SIM-FX-MOM',
    slug: 'fx-momentum-sim',
    name: 'FX momentum sim',
    description: 'Draft FX momentum paper-trading simulation queued for execution.',
    namespace: 'fx',
    family: 'momentum',
    stage: 'SCENARIO_CONFIGURATION',
    version: '0.1.0',
    scenario: {
      id: 'SCN-4',
      label: 'Intraday',
      universe: 'G10 FX',
      startDate: '2025-01-01',
      endDate: '2025-12-31',
      fillModel: 'spread',
      venueModel: 'consolidated',
      latencyModel: 'fixed-20ms',
      parameters: [],
      notes: 'Awaiting configuration.',
    },
    run: {
      id: 'RUN-0',
      status: 'QUEUED',
      attempt: 0,
      progress: 0,
      note: 'Queued for the simulator.',
    },
    runs: [
      { id: 'RUN-0', status: 'QUEUED', attempt: 0, progress: 0, note: 'Queued for the simulator.' },
    ],
    orders: [],
    fills: [],
    positions: [],
    portfolio: {
      baseCurrency: 'USD',
      cash: '1000000',
      equity: '1000000',
      grossExposure: '0',
      netExposure: '0',
      realizedPnl: '0',
      unrealizedPnl: '0',
    },
    timeline: [
      {
        id: 'TL-8',
        kind: 'SESSION',
        label: 'Session drafted',
        detail: 'Configuration in progress.',
        at: '2026-08-01T00:00:00.000Z',
      },
    ],
    replays: [],
    metrics: [],
    validation: { status: 'NOT_RUN', method: 'Point-in-time', note: 'Validation not yet run.' },
    approval: 'NOT_REQUESTED',
    reviews: [],
    approvals: [],
    reports: [],
    artifacts: [],
    dependencies: [
      {
        id: 'SDEP-7',
        kind: 'PORTFOLIO',
        ref: 'pf-fx-mom-draft',
        name: 'FX momentum draft',
        status: 'PENDING',
      },
    ],
    lineage: {
      nodes: [
        { id: 'N-1', kind: 'PORTFOLIO', ref: 'pf-fx-mom-draft', label: 'FX momentum draft' },
        { id: 'N-2', kind: 'SIMULATION', ref: 'sim-fx-mom', label: 'FX momentum sim' },
      ],
      edges: [{ from: 'N-1', to: 'N-2' }],
    },
    versions: [
      {
        version: '0.1.0',
        stage: 'SCENARIO_CONFIGURATION',
        createdAt: '2026-08-01T00:00:00.000Z',
        note: 'Draft.',
        manifestHash: 'sha256:simfx01',
      },
    ],
    snapshots: [],
    owner: { owner: 'Dara Trader', team: 'Macro Execution', steward: 'Execution Guild' },
    tags: ['momentum', 'fx', 'draft'],
    metadata: [
      { key: 'universe', value: 'G10 FX' },
      { key: 'mode', value: 'paper' },
    ],
    portfolioRef: 'pf-fx-mom-draft',
    registryRef: 'REG-sim-fx-mom',
    registeredAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'SIM-VOL-CANCELLED',
    slug: 'vol-target-sim',
    name: 'Vol target sim (cancelled)',
    description: 'Volatility-target paper-trading simulation cancelled mid-run; awaiting retry.',
    namespace: 'equities',
    family: 'volatility',
    stage: 'QUEUED',
    version: '0.3.0',
    templateRef: 'TPL-EQUITY-DAILY',
    scenario: {
      id: 'SCN-5',
      label: 'Weekly rebalance',
      universe: 'US options',
      startDate: '2025-01-01',
      endDate: '2025-12-31',
      fillModel: 'impact',
      venueModel: 'consolidated',
      latencyModel: 'fixed-80ms',
      parameters: [{ key: 'tenor', value: '30d' }],
      notes: 'Cancelled; awaiting data fix.',
    },
    run: {
      id: 'RUN-5',
      status: 'CANCELLED',
      attempt: 1,
      progress: 18,
      startedAt: '2026-07-26T00:00:00.000Z',
      endedAt: '2026-07-26T00:30:00.000Z',
      note: 'Cancelled by researcher (data issue).',
    },
    runs: [
      {
        id: 'RUN-5',
        status: 'CANCELLED',
        attempt: 1,
        progress: 18,
        startedAt: '2026-07-26T00:00:00.000Z',
        endedAt: '2026-07-26T00:30:00.000Z',
        note: 'Cancelled by researcher (data issue).',
      },
    ],
    orders: [
      {
        id: 'ORD-7',
        clientOrderId: 'C-5001',
        symbol: 'SPX',
        side: 'SELL',
        type: 'LIMIT',
        quantity: '10',
        limitPrice: '5200.00',
        filledQuantity: '0',
        status: 'CANCELLED',
        createdAt: '2026-07-26T00:05:00.000Z',
      },
    ],
    fills: [],
    positions: [],
    portfolio: {
      baseCurrency: 'USD',
      cash: '1000000',
      equity: '1000000',
      grossExposure: '0',
      netExposure: '0',
      realizedPnl: '0',
      unrealizedPnl: '0',
    },
    timeline: [
      {
        id: 'TL-9',
        kind: 'SESSION',
        label: 'Session started',
        detail: 'Simulation started.',
        at: '2026-07-26T00:00:00.000Z',
      },
      {
        id: 'TL-10',
        kind: 'ORDER',
        label: 'Order cancelled',
        detail: 'SPX 10 cancelled.',
        at: '2026-07-26T00:30:00.000Z',
      },
    ],
    replays: [],
    metrics: [],
    validation: { status: 'PENDING', method: 'Point-in-time', note: 'Pending data fix.' },
    approval: 'NOT_REQUESTED',
    reviews: [],
    approvals: [],
    reports: [],
    artifacts: [],
    dependencies: [
      {
        id: 'SDEP-8',
        kind: 'DATASET',
        ref: 'ds-cme-es-index',
        name: 'CME ES index prices',
        status: 'MISSING',
      },
    ],
    lineage: {
      nodes: [
        {
          id: 'N-1',
          kind: 'SIMULATION',
          ref: 'sim-vol-cancelled',
          label: 'Vol target sim (cancelled)',
        },
      ],
      edges: [],
    },
    versions: [
      {
        version: '0.3.0',
        stage: 'QUEUED',
        createdAt: '2026-07-26T00:00:00.000Z',
        note: 'Queued after cancel.',
        manifestHash: 'sha256:simvol03',
      },
    ],
    snapshots: [],
    owner: { owner: 'Dara Trader', team: 'Volatility Execution', steward: 'Execution Guild' },
    tags: ['volatility', 'vol-target', 'cancelled'],
    metadata: [
      { key: 'universe', value: 'US options' },
      { key: 'mode', value: 'paper' },
    ],
    portfolioRef: 'pf-vol-cancelled',
    registryRef: 'REG-sim-vol-cancelled',
    registeredAt: '2026-07-25T00:00:00.000Z',
    updatedAt: '2026-07-26T00:30:00.000Z',
  },
];

export const FAMILIES: readonly SimulationFamily[] = [
  {
    namespace: 'equities',
    family: 'market-neutral',
    description: 'Market-neutral equity simulations.',
    sessionCount: 1,
  },
  {
    namespace: 'equities',
    family: 'volatility',
    description: 'Volatility-target simulations.',
    sessionCount: 1,
  },
  {
    namespace: 'multi-asset',
    family: 'risk-balanced',
    description: 'Risk-balanced multi-asset simulations.',
    sessionCount: 1,
  },
  {
    namespace: 'credit',
    family: 'carry',
    description: 'Credit carry simulations.',
    sessionCount: 1,
  },
  { namespace: 'fx', family: 'momentum', description: 'FX momentum simulations.', sessionCount: 1 },
];

export const TEMPLATES: readonly ScenarioTemplate[] = [
  {
    id: 'TPL-EQUITY-DAILY',
    name: 'Equity daily',
    description: 'Daily-close participation-aware equity template.',
    fillModel: 'participation-aware',
    venueModel: 'consolidated',
  },
  {
    id: 'TPL-MULTI-ASSET',
    name: 'Multi-asset',
    description: 'Multi-venue spread+impact sleeve template.',
    fillModel: 'spread + impact',
    venueModel: 'multi-venue',
  },
  {
    id: 'TPL-INTRADAY',
    name: 'Intraday',
    description: 'Low-latency intraday spread template.',
    fillModel: 'spread',
    venueModel: 'consolidated',
  },
];

export const COMPARISONS: readonly SimulationComparison[] = [
  {
    id: 'SCMP-1',
    name: 'Equity vs multi-asset (execution quality)',
    sessionIds: ['SIM-EQUITY-MN', 'SIM-MULTI-ASSET'],
    metricKeys: ['fill_rate', 'avg_slippage', 'reject_rate', 'sim_latency', 'participation'],
    createdAt: '2026-07-29T00:00:00.000Z',
    note: 'Head-to-head execution quality of the two completed sims.',
  },
];
